# apfs_hfs_convert
# Autogenerated from man page /usr/share/man/man8/apfs_hfs_convert.8
complete -c apfs_hfs_convert -s e --description 'Estimate the APFS metadata size after conversion.'
complete -c apfs_hfs_convert -s v --description 'Increase verbosity of the output.'
complete -c apfs_hfs_convert -s s --description 'Force the converted volume to be case-sensitive.'
complete -c apfs_hfs_convert -s S --description 'Print statistics about the conversion to the supplied path.'
complete -c apfs_hfs_convert -s n --description 'Do not finalize the conversion to APFS.  Volume remains HFS.'
complete -c apfs_hfs_convert -s f --description 'Force conversion if volume is dirty (journal is non-empty, volume had inconsi…'
complete -c apfs_hfs_convert -s F --description 'Volume number index (0-based) should be formatted as fixed-size.'
complete -c apfs_hfs_convert -s M --description 'When converting LwVM systems, which require a special "conversion mount" of t…'
complete -c apfs_hfs_convert -s o --description 'NX or APFS format options.'
complete -c apfs_hfs_convert -s D --description 'Convert all former and current directory hardlinks to files/aliases.'

