# appleeventsd
# Autogenerated from man page /usr/share/man/man8/appleeventsd.8
complete -c appleeventsd -l server --description '.'
complete -c appleeventsd -l noStartupNotification --description '.'

