# apply
# Autogenerated from man page /usr/share/man/man1/apply.1
complete -c apply -s '#' --description 'Normally arguments are taken singly; the optional number # specifies the numb…'
complete -c apply -s a --description 'The use of the character % as a magic character may be changed with the a opt…'
complete -c apply -s d --description 'Display the commands that would have been executed, but do not actually execu…'

