# apt
# Autogenerated from man page /usr/share/man/man1/apt.1
complete -c apt -s s --description 'Specify the directory root under which processor-generated  source files will…'
complete -c apt -o nocompile --description 'Do not compile sources files to class files. if t.'
complete -c apt -o print --description 'Print out textual representation of specified types;  perform no annotation p…'
complete -c apt -s A --description 'Options to pass to annotation processors -- these are  not interpreted by apt…'
complete -c apt -o factorypath --description 'Specify where to find annotation processor factories; if  this option is used…'
complete -c apt -o factory --description 'Name of annotation processor factory to use;  bypasses default discovery proc…'
complete -c apt -s d --description 'Specify where to place processor and javac generated class files  . if t.'
complete -c apt -o cp --description 'or . if t.'
complete -c apt -o classpath --description 'Specify where to find user class files and annotation processor  factories.'

