# arp
# Autogenerated from man page /usr/share/man/man8/arp.8
complete -c arp -s a --description 'The program displays or deletes all of the current ARP entries.'
complete -c arp -s d --description 'A super-user may delete an entry for the host called hostname with the d flag.'
complete -c arp -s i --description 'Limit the operation scope to the ARP entries on interface.'
complete -c arp -s l --description 'Show link-layer reachability information.'
complete -c arp -s n --description 'Show network addresses as numbers (normally arp attempts to display addresses…'
complete -c arp -s s --description 'Create an ARP entry for the host called hostname with the Ethernet address et…'
complete -c arp -s S --description 'Is just like s except any existing ARP entry for this host will be deleted fi…'
complete -c arp -s f --description 'Cause the file filename to be read and multiple entries to be set in the ARP …'
complete -c arp -s x --description 'Show extended link-layer reachability information in addition to that shown b…'

