# asctl
# Autogenerated from man page /usr/share/man/man1/asctl.1
complete -c asctl -s p --description 'By default, asctl displays paths relative to the user\'s home directory.'
complete -c asctl -s l --description 'Write internal logging information to a temporary file.'

