# assetutil
# Autogenerated from man page /usr/share/man/man1/assetutil.1
complete -c assetutil -s V --description 'version information for assetutil.'
complete -c assetutil -s I --description 'Produce a JSON description of the asset catalog object with the given name to…'
complete -c assetutil -s i --description 'Keep all assets that have idiom that is given on the command line.'
complete -c assetutil -s s --description 'Keep all assets that have scale factor that is given on the command line, pre…'
complete -c assetutil -s p --description 'Keep all assets that have the display gamut that is given on the command line…'
complete -c assetutil -s M --description 'Keep all assets that have memory class that is given on the command line, pre…'
complete -c assetutil -s g --description 'Keep all assets that have graphics class that is given on the command line.'
complete -c assetutil -s h --description 'process the hosted idioms list, this is a list of the idioms that must always…'
complete -c assetutil -s t --description 'Subtype to keep (integer).'
complete -c assetutil -s c --description 'Main Assets.'
complete -c assetutil -s o --description 'Output file name, if no output file is given then input file is overwritten.'
complete -c assetutil -s T --description 'compare thinning attributes \'scale=2:idiom=phone:memory=2:graphicsclass=MTL1,…'

