# atos
# Autogenerated from man page /usr/share/man/man1/atos.1
complete -c atos -s o --description 'The path to a binary image file in which to look up symbols.'
complete -c atos -s p --description 'The process ID or the partial name of a currently executing process in which …'
complete -c atos -o arch --description 'The particular architecure of a binary image file in which to look up symbols.'
complete -c atos -s l --description 'The load address of the binary image.'
complete -c atos -s s --description 'The slide value of the binary image -- this is the difference between the loa…'
complete -c atos -o printHeader --description 'If a process was specified, the first line of atos output should be a header …'
complete -c atos -o fullPath --description 'Print the full path of the source files.'

