# audit
# Autogenerated from man page /usr/share/man/man8/audit.8
complete -c audit -s e --description 'Forces the audit system to immediately remove audit log files that meet the e…'
complete -c audit -s i --description 'Initializes and starts auditing.'
complete -c audit -s n --description 'Forces the audit system to close the existing audit log file and rotate to a …'
complete -c audit -s s --description 'Specifies that the audit system should [re]synchronize its configuration from…'
complete -c audit -s t --description 'Specifies that the audit system should terminate.'

