# automountd
# Autogenerated from man page /usr/share/man/man8/automountd.8
complete -c automountd -s v --description 'Log to syslogd 8 more detailed information about actions taken by automountd.'
complete -c automountd -s n --description 'Disable browsing of all maps.'
complete -c automountd -s T --description 'Increase by 1 the logging level for messages printed to the standard output i…'
complete -c automountd -s o --description 'Apply the options specified by opts to all mounts by default.'
complete -c automountd -s D --description 'Set the environment value specified by name to the specified value.'

