# automount
# Autogenerated from man page /usr/share/man/man8/automount.8
complete -c automount -s v --description 'Print more detailed information about actions taken by automount.'
complete -c automount -s c --description 'Tell automountd 8 to flush any cached information it has.'
complete -c automount -s u --description 'Unmount all non-busy automounted mounts.  Top-level triggers are preserved.'
complete -c automount -s t --description 'Set to timeout seconds the time after which an automounted file system will b…'

