# BacklightdTester
# Autogenerated from man page /usr/share/man/man1/BacklightdTester.1
complete -c BacklightdTester -s a --description 'Description of -a flag.'
complete -c BacklightdTester -s b --description 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

