# banner
# Autogenerated from man page /usr/share/man/man6/banner.6
complete -c banner -s d --description 'Enable debug.'
complete -c banner -s t --description 'Enable trace.'
complete -c banner -s w --description 'Change the output from a width of 132 to width, suitable for a narrow termina…'

