# bioutil
# Autogenerated from man page /usr/share/man/man1/bioutil.1
complete -c bioutil -s r --description 'Read Touch ID configuration.'
complete -c bioutil -s w --description 'Write Touch ID configuration.'
complete -c bioutil -s s --description 'Indicates that system-wide configuration is to be read/written (user-specific…'
complete -c bioutil -s f --description 'Enables (1) or disables (0) overall Touch ID functionality (system-wide confi…'
complete -c bioutil -s u --description 'Enables (1) or disables (0) Touch ID for unlock.'
complete -c bioutil -s a --description 'Enables (1) or disables (0) Touch ID for ApplePay (user-specific configuratio…'
complete -c bioutil -s c --description 'Provides number of enrolled fingerprints of the current user or of all users …'
complete -c bioutil -s p --description 'Deletes all enrolled fingerprints of the current user or of all users (when r…'
complete -c bioutil -s d --description 'Deletes all enrolled fingerprints of the user with given user ID (must be run…'

