# bitcode_strip
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/bitcode_strip.1
complete -c bitcode_strip -s o --description 'specifies the output file as  output.'
complete -c bitcode_strip -s r --description 'specifies the bitcode segment is to be removed.'
complete -c bitcode_strip -s m --description 'specifies the bitcode segment is to be removed and a marker is left.'
complete -c bitcode_strip -s l --description 'specifies that only the bitcode segment and the (__TEXT,__info_plist) section…'

