# bootpd
# Autogenerated from man page /usr/share/man/man8/bootpd.8
complete -c bootpd -s B --description 'Disable BOOTP service.'
complete -c bootpd -s b --description 'Only respond if the client\'s bootfile exists: for BOOTP clients only.'
complete -c bootpd -s D --description 'Enable DHCP service.   By default, DHCP service is disabled.'
complete -c bootpd -s d --description 'Remain in the foreground and produce extra debugging output to stderr.'
complete -c bootpd -s I --description 'Disable re-initialization on IP address changes.'
complete -c bootpd -s i --description 'Enable service on the specified interface.'
complete -c bootpd -s m --description 'Enable NetBoot 1. 0 (BOOTP-based) service.'
complete -c bootpd -s N --description 'Enable NetBoot 2. 0 (BSDP/DHCP-based) service.'
complete -c bootpd -s o --description 'For relay agent operation, the maximum hop count, default is 4 hops.'
complete -c bootpd -s q --description 'Be quiet as possible.   Only report serious errors to.'
complete -c bootpd -s r --description 'Relay packets to the specified server_ip, not exceeding the hop count.'
complete -c bootpd -s S --description 'Enable BOOTP service.'
complete -c bootpd -s v --description 'Be more verbose in messages logged to \\fI/var/log/system. log\\fR.'

