# brew
# Autogenerated from man page /usr/local/share/man/man1/brew.1
complete -c brew -l cache --description 'Display Homebrew\'s download cache.  See also HOMEBREW_CACHE.'
complete -c brew -l cellar --description 'Display Homebrew\'s Cellar path.'
complete -c brew -l env -l shell -l plain --description 'Show a summary of the Homebrew build environment as a plain list.'
complete -c brew -l prefix --description 'Display Homebrew\'s install path.  Default: /usr/local.'
complete -c brew -l repository --description 'Display where Homebrew\'s . git directory is located.'
complete -c brew -l version --description 'Print the version number of Homebrew to standard output and exit.'

