# BuildStrings
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/BuildStrings.1
complete -c BuildStrings -o header --description 'Generate a header file.   If not provided, default is resource file format.'
complete -c BuildStrings -o define --description 'Defines variable for use in #ifdef or #ifndef conditionals.'
complete -c BuildStrings -o id --description 'The resource ID for the STR# resource.'
complete -c BuildStrings -o attributes --description 'Resource attributes for the STR# resource definition (such as locked, preload…'
complete -c BuildStrings -o type --description 'Customizes three preprocessor variables (MinValidFoo, MaxValidFoo, FooRsrcID)…'
complete -c BuildStrings -o in --description 'The input file, a set of newline-separated pairs of newline-separated strings.'
complete -c BuildStrings -o out --description 'The output file.'

