# calendar
# Autogenerated from man page /usr/share/man/man1/calendar.1
complete -c calendar -s A --description 'Print lines from today and the next num days (forward, future).'
complete -c calendar -s a --description 'Process the ``calendar\'\' files of all users and mail the results to them.'
complete -c calendar -s B --description 'Print lines from today and the previous num days (backward, past).'
complete -c calendar -s F --description 'Specify which day of the week is ``Friday\'\' (the day before the weekend begin…'
complete -c calendar -s f --description 'Use calendarfile as the default calendar file.  t off dd .  Ar mm Op .'
complete -c calendar -s W --description 'Print lines from today and the next num days (forward, future).'

