# cdknowledgetool
# Autogenerated from man page /usr/share/man/man1/cdknowledgetool.1
complete -c cdknowledgetool -s a --description 'Description of -a flag.'
complete -c cdknowledgetool -s b --description 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

