# checknr
# Autogenerated from man page /usr/share/man/man1/checknr.1
complete -c checknr -s a --description 'Add additional pairs of macros to the list of known macros.'
complete -c checknr -s c --description 'Define commands which would otherwise be complained about as undefined.'
complete -c checknr -s f --description 'Request checknr to ignore \\ef font changes.'
complete -c checknr -s s --description 'Ignore \\es size changes.'

