# chflags
# Autogenerated from man page /usr/share/man/man1/chflags.1
complete -c chflags -s f --description 'Do not display a diagnostic message if chflags could not modify the flags for…'
complete -c chflags -s H --description 'If the R option is specified, symbolic links on the command line are followed.'
complete -c chflags -s h --description 'If the file is a symbolic link, change the file flags of the link itself rath…'
complete -c chflags -s L --description 'If the R option is specified, all symbolic links are followed.'
complete -c chflags -s P --description 'If the R option is specified, no symbolic links are followed.'
complete -c chflags -s R --description 'Change the file flags for the file hierarchies rooted in the files instead of…'
complete -c chflags -s v --description 'Cause chflags to be verbose, showing filenames as the flags are modified.'

