# chgrp
# Autogenerated from man page /usr/share/man/man1/chgrp.1
complete -c chgrp -s f --description 'The force option ignores errors, except for usage errors and doesn\'t query ab…'
complete -c chgrp -s H --description 'If the R option is specified, symbolic links on the command line are followed.'
complete -c chgrp -s h --description 'If the file is a symbolic link, the group ID of the link itself is changed ra…'
complete -c chgrp -s L --description 'If the R option is specified, all symbolic links are followed.'
complete -c chgrp -s P --description 'If the R option is specified, no symbolic links are followed.'
complete -c chgrp -s R --description 'Change the group ID for the file hierarchies rooted in the files instead of j…'
complete -c chgrp -s v --description 'Cause chgrp chgrp to be verbose, showing files as the group is modified.'

