# chkpasswd
# Autogenerated from man page /usr/share/man/man8/chkpasswd.8
complete -c chkpasswd -s c --description 'The supplied password is compared verbatim without first being encrypted.'
complete -c chkpasswd -s i --description 'Specify the system against which to check the password (default is PAM).'
complete -c chkpasswd -s l --description 'Specify a location; varies based on infosystem type: -tag -width "for opendir…'

