# chmod
# Autogenerated from man page /usr/share/man/man1/chmod.1
complete -c chmod -s f --description 'Do not display a diagnostic message if chmod chmod could not modify the mode …'
complete -c chmod -s H --description 'If the R option is specified, symbolic links on the command line are followed.'
complete -c chmod -s h --description 'If the file is a symbolic link, change the mode of the link itself rather tha…'
complete -c chmod -s L --description 'If the R option is specified, all symbolic links are followed.'
complete -c chmod -s P --description 'If the R option is specified, no symbolic links are followed.'
complete -c chmod -s R --description 'Change the modes of the file hierarchies rooted in the files instead of just …'
complete -c chmod -s v --description 'Cause chmod chmod to be verbose, showing filenames as the mode is modified.'
complete -c chmod -s a --description 'The -a mode is used to delete ACL entries.'
complete -c chmod -s E --description 'Reads the ACL information from stdin, as a sequential list of ACEs, separated…'
complete -c chmod -s C --description 'Returns false if any of the named files have ACLs in non-canonical order.'
complete -c chmod -s i --description 'Removes the \'inherited\' bit from all entries in the named file(s) ACLs.'
complete -c chmod -s I --description 'Removes all inherited entries from the named file(s) ACL(s).'
complete -c chmod -s N --description 'Removes the ACL from the named file(s).'

