# chown
# Autogenerated from man page /usr/share/man/man8/chown.8
complete -c chown -s f --description 'Don\'t report any failure to change file owner or group, nor modify the exit s…'
complete -c chown -s H --description 'If the R option is specified, symbolic links on the command line are followed.'
complete -c chown -s h --description 'If the file is a symbolic link, change the user ID and/or the group ID of the…'
complete -c chown -s L --description 'If the R option is specified, all symbolic links are followed.'
complete -c chown -s P --description 'If the R option is specified, no symbolic links are followed.'
complete -c chown -s R --description 'Change the user ID and/or the group ID for the file hierarchies rooted in the…'
complete -c chown -s v --description 'Cause chown chown to be verbose, showing files as the owner is modified.'

