# chpass
# Autogenerated from man page /usr/share/man/man1/chpass.1
complete -c chpass -s l --description 'If not specified, chpass will perform a search for the user record on all ava…'
complete -c chpass -s u --description 'The user name to use when authenticating to the directory node containing the…'
complete -c chpass -s s --description 'Attempt to change the user\'s shell to newshell.'

