# codesign_allocate
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/codesign_allocate.1
complete -c codesign_allocate -s i --description 'specifies the input file as  oldfile.'
complete -c codesign_allocate -s o --description 'specifies the output file as  newfile.'
complete -c codesign_allocate -s a --description 'specifies for the architecture  arch that the size of the code signing data i…'
complete -c codesign_allocate -s A --description 'specifies for the architecture as a pair of decimal integers for the cputype …'
complete -c codesign_allocate -s r --description 'remove the code signature date and the LC_CODE_SIGNATURE load command.'
complete -c codesign_allocate -s p --description 'page align the code signature data by padding string table and changing its s…'

