# configd
# Autogenerated from man page /usr/share/man/man8/configd.8
complete -c configd -s b --description 'Don\'t actually load any bundles.'
complete -c configd -s B --description 'Prevents the loading of the bundle with the specified bundleID.'
complete -c configd -s d --description 'Run configd in the foreground without forking.   This is useful for debugging.'
complete -c configd -s v --description 'Puts configd into verbose mode.'
complete -c configd -s V --description 'Turns verbose mode on for the bundle with the specified bundleID.'
complete -c configd -s t --description 'Loads only the bundle specified by bundle-path.'

