# corelist5
# Autogenerated from man page /usr/share/man/man1/corelist5.18.1
complete -c corelist5 -s a --description 'lists all versions of the given module (or the matching modules, in case you …'
complete -c corelist5 -s d --description 'finds the first perl version where a module has been released by date, and no…'
complete -c corelist5 -l diff --description 'Given two versions of perl, this prints a human-readable table of all module …'
complete -c corelist5 -s '?' -o help --description 'help! help! help! to see more help, try --man.'
complete -c corelist5 -o man --description 'all of the help.'
complete -c corelist5 -s v --description 'lists all of the perl release versions we got the CoreList for.'
complete -c corelist5 -s r --description 'lists all of the perl releases and when they were released .'
complete -c corelist5 -l feature -s f --description 'lists the first version bundle of each named feature given.'

