# CpMac
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/CpMac.1
complete -c CpMac -s r --description 'If source designates a directory, CpMac copies the directory and the entire s…'
complete -c CpMac -s p --description 'Causes CpMac to preserve in the copy as many of the modification time, access…'
complete -c CpMac -o mac --description 'Allows use of HFS-style paths for both source and target.'

