# createhomedir
# Autogenerated from man page /usr/share/man/man1/createhomedir.1
complete -c createhomedir -s s --description 'creates home directories for server home paths only (default).'
complete -c createhomedir -s c --description 'creates home directories for local home paths only.'
complete -c createhomedir -s b --description 'creates home directories for both server and local home paths.'
complete -c createhomedir -s a --description 'creates home directories for users defined in all directory domains of the se…'
complete -c createhomedir -s l --description 'creates home directories for users defined in the local directory domain.'
complete -c createhomedir -s L --description 'causes the created home directory to be localized.'
complete -c createhomedir -s n --description 'creates home directories for users defined in a specific directory domain in …'
complete -c createhomedir -s u --description 'creates a home directory for a specific user defined in the domain(s) identif…'
complete -c createhomedir -s i --description 'reads username list from standard input and creates specified home directorie…'
complete -c createhomedir -s h --description 'usage help.'

