# crontab
# Autogenerated from man page /usr/share/man/man1/crontab.1
complete -c crontab -s u --description 'Specify the name of the user whose crontab is to be tweaked.'
complete -c crontab -s l --description 'Display the current crontab on standard output.'
complete -c crontab -s r --description 'Remove the current crontab.'
complete -c crontab -s e --description 'Edit the current crontab using the editor specified by the VISUAL or EDITOR e…'

