# csgather
# Autogenerated from man page /usr/share/man/man1/csgather.1
complete -c csgather -s G --description 'Gather all CoreStorage metadata and write into the specified directory.'
complete -c csgather -s o --description 'Specify the output file generated by the -r option.'
complete -c csgather -s r --description 'Find out the CoreStorage logical volume identified by the given mount point, …'

