# csplit
# Autogenerated from man page /usr/share/man/man1/csplit.1
complete -c csplit -s f --description 'Give created files names beginning with prefix.  The default is xx.'
complete -c csplit -s k --description 'Do not remove output files if an error occurs or a HUP, INT or TERM signal is…'
complete -c csplit -s n --description 'Use number of decimal digits after the prefix to form the file name.'
complete -c csplit -s s --description 'Do not write the size of each output file to standard output as it is created.'

