# csreq
# Autogenerated from man page /usr/share/man/man1/csreq.1
complete -c csreq -s b --description 'Requests that the requirement read be written in binary form to the path give…'
complete -c csreq -s r --description 'Specifies the input requirement.  See "specifying requirements" below.'
complete -c csreq -s t --description 'Requests that the requirement read be written as text to standard output.'
complete -c csreq -s v --description 'Increases the verbosity of output.'

