# csunique
# Autogenerated from man page /usr/share/man/man8/csunique.8
complete -c csunique -s v --description 'Output verbose progress information of each step and the UUID re-mappings.'
complete -c csunique -s n --description 'Operates in "dry run" mode; no changes are made to the on-disk data.'
complete -c csunique -s I --description 'Specifies an additional class of UUID objects that should be modified.'
complete -c csunique -s X --description 'Specifies a class of UUID objects that should not be modified.'

