# cxattr
# Autogenerated from man page /usr/share/man/man1/cxattr.1
complete -c cxattr -s a --description 'Description of -a flag.'
complete -c cxattr -s b --description 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

