# date
# Autogenerated from man page /usr/share/man/man1/date.1
complete -c date -s d --description 'Set the kernel\'s value for daylight saving time.'
complete -c date -s f --description 'Use input_fmt as the format string to parse the new_date provided rather than…'
complete -c date -s j --description 'Do not try to set the date.'
complete -c date -s n --description 'By default, if the timed 8 daemon is running, date sets the time on all of th…'
complete -c date -s R --description 'Use RFC 2822 date and time output format.'
complete -c date -s r --description 'Print the date and time represented by seconds, where seconds is the number o…'
complete -c date -s t --description 'Set the system\'s value for minutes west of GMT.'
complete -c date -s u --description 'Display or set the date in UTC (Coordinated Universal) time.'
complete -c date -s v --description 'Adjust (i. e.'

