# db_checkpoint
# Autogenerated from man page /usr/share/man/man1/db_checkpoint.1
complete -c db_checkpoint -s 1 --description 'Checkpoint the log once, regardless of whether or not there has been activity…'
complete -c db_checkpoint -s h --description 'Specify a home directory for the database environment; by default, the curren…'
complete -c db_checkpoint -s k --description 'Checkpoint the database at least as often as every kbytes of log file are wri…'
complete -c db_checkpoint -s L --description 'Log the execution of the db_checkpoint utility to the specified file in the f…'
complete -c db_checkpoint -s P --description 'Specify an environment password.'
complete -c db_checkpoint -s p --description 'Checkpoint the database at least every min minutes if there has been any acti…'
complete -c db_checkpoint -s V --description 'Write the library version number to the standard output, and exit.'
complete -c db_checkpoint -s v --description 'Write the time of each checkpoint attempt to the standard output.'

