# db_deadlock
# Autogenerated from man page /usr/share/man/man1/db_deadlock.1
complete -c db_deadlock -s a --description 'When a deadlock is detected, abort the locker: -tag -width m with the greates…'
complete -c db_deadlock -s h --description 'Specify a home directory for the database environment; by default, the curren…'
complete -c db_deadlock -s L --description 'Log the execution of the db_deadlock utility to the specified file in the fol…'
complete -c db_deadlock -s t --description 'Check the database environment every sec seconds plus usec microseconds to se…'
complete -c db_deadlock -s V --description 'Write the library version number to the standard output, and exit.'
complete -c db_deadlock -s v --description 'Run in verbose mode, generating messages each time the detector runs.'

