# db_load
# Autogenerated from man page /usr/share/man/man1/db_load.1
complete -c db_load -s c --description 'Specify configuration options ignoring any value they may have based on the i…'
complete -c db_load -s f --description 'Read from the specified input file instead of from the standard input.'
complete -c db_load -s h --description 'Specify a home directory for the database environment.'
complete -c db_load -s n --description 'Do not overwrite existing keys in the database when loading into an already e…'
complete -c db_load -s P --description 'Specify an environment password.'
complete -c db_load -s T --description 'The -T option allows non-Berkeley DB applications to easily load text files i…'
complete -c db_load -s t --description 'Specify the underlying access method.'
complete -c db_load -s V --description 'Write the library version number to the standard output, and exit.'

