# db_upgrade
# Autogenerated from man page /usr/share/man/man1/db_upgrade.1
complete -c db_upgrade -s h --description 'Specify a home directory for the database environment; by default, the curren…'
complete -c db_upgrade -s N --description 'Do not acquire shared region mutexes while running.'
complete -c db_upgrade -s P --description 'Specify an environment password.'
complete -c db_upgrade -s s --description 'This flag is only meaningful when upgrading databases from releases before th…'
complete -c db_upgrade -s V --description 'Write the library version number to the standard output, and exit.'

