# dbiprof5
# Autogenerated from man page /usr/share/man/man1/dbiprof5.18.1
complete -c dbiprof5 -l number --description 'Produce this many items in the report.   Defaults to 10.'
complete -c dbiprof5 -l sort --description 'Sort results by the given field.'
complete -c dbiprof5 -l reverse --description 'Reverses the selected sort.'
complete -c dbiprof5 -l match --description 'Consider only items where the specified key matches the given value.'
complete -c dbiprof5 -l exclude --description 'Remove items for where the specified key matches the given value.'
complete -c dbiprof5 -l case-sensitive --description 'Using this option causes --match and --exclude to work case-sensitively.'
complete -c dbiprof5 -l delete --description 'Sets the \\f(CW\\*(C`DeleteFiles\\*(C\' option to DBI::ProfileData which causes t…'
complete -c dbiprof5 -l dumpnodes --description 'Print the list of nodes in the form of a perl data structure.'

