# defaults
# Autogenerated from man page /usr/share/man/man1/defaults.1
complete -c defaults -o app --description 'The name of an application may be provided instead of a domain using the \\fB-…'
complete -c defaults -s g --description 'Specify the global domain.'
complete -c defaults -o string --description 'Allows the user to specify a string as the value for the given preference key.'
complete -c defaults -o data --description 'Allows the user to specify a bunch of raw data bytes as the value for the giv…'
complete -c defaults -o int --description 'Allows the user to specify an integer as the value for the given preference k…'
complete -c defaults -o float --description 'Allows the user to specify a floating point number as the value for the given…'
complete -c defaults -o bool --description 'Allows the user to specify a boolean as the value for the given preference ke…'
complete -c defaults -o date --description 'Allows the user to specify a date as the value for the given preference key.'
complete -c defaults -o array --description 'Allows the user to specify an array as the value for the given preference key…'
complete -c defaults -o array-add --description 'Allows the user to add new elements to the end of an array for a key which ha…'
complete -c defaults -o dict --description 'Allows the user to add a dictionary to the defaults database for a domain.'
complete -c defaults -o dict-add --description 'Allows the user to add new key/value pairs to a dictionary for a key which ha…'
complete -c defaults -o currentHost --description 'Restricts preferences operations to the host the user is currently logged in …'
complete -c defaults -o host --description 'Restricts preferences operations to \\fIhostname\\fR.'

