# defragcli
# Autogenerated from man page /usr/share/man/man8/defragcli.8
complete -c defragcli -s d --description 'Dry mode, will not adjust kernel parameters.'
complete -c defragcli -s f --description 'Force defragmentation attempt even on mounts that do not normally qualify.'
complete -c defragcli -s c --description 'Path to a defragmentation configuration plist file.'
complete -c defragcli -s t --description 'Maximum time for defragcli to run before stopping.'
complete -c defragcli -s u --description 'User ID of user\'s home directory to defragment, default is current user if ru…'

