# DeRez
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/DeRez.1
complete -c DeRez -s c --description 'Generates output that is backward-compatible with   Rez  1. 0.'
complete -c DeRez -s d --description 'Defines the macro variable   macro  as having the value   data.'
complete -c DeRez -s e --description 'Prints characters that are normally escaped, such as \\\\0xff, as extended Maci…'
complete -c DeRez -s i --description 'Specifies the directory to search for   #include  files.'
complete -c DeRez -o is --description 'Specifies the system SDK in which to search for include files and frameworks.'
complete -c DeRez -s m --description 'Sets the maximum output string width to   n,  where   n  must be in the range…'
complete -c DeRez -o noResolve --description 'Suppresses leaf alias resolution of the file or pathname for the input resour…'
complete -c DeRez -o only --description 'Reads only resources of the type indicated by   typeExpr.'
complete -c DeRez -s p --description 'Writes progress and summary information to standard output.'
complete -c DeRez -o rd --description 'Suppresses warning messages emitted when a resource type is redeclared.'
complete -c DeRez -o script --description 'Enables the recognition of any of several 2-byte character script systems to …'
complete -c DeRez -s s --description 'Skips resources of the type indicated by   typeExpr.'
complete -c DeRez -o skip --description 'br -skip -only "\'MENU\' ("\'"Edit"\'")".'
complete -c DeRez -s u --description 'Undefines the preset macro variable  macro.   This is the same as writing.'
complete -c DeRez -o useDF --description 'Reads and writes resource information from the files\' data forks, instead of …'

