# dnctl
# Autogenerated from man page /usr/share/man/man8/dnctl.8
complete -c dnctl -s a --description 'While listing, show counter values.'
complete -c dnctl -s f --description 'Don\'t ask for confirmation for commands that can cause problems if misused, i.'
complete -c dnctl -s h --description 'Displays a short help.'
complete -c dnctl -s n --description 'Only check syntax of the command strings, without actually passing them to th…'
complete -c dnctl -s q --description 'While add Ns ing, zero Ns ing, resetlog Ns ging or flush Ns ing, be quiet abo…'
complete -c dnctl -s s --description 'While listing pipes, sort according to one of the four counters (total or cur…'
complete -c dnctl -s v --description 'Be verbose.'

