# dscacheutil
# Autogenerated from man page /usr/share/man/man1/dscacheutil.1
complete -c dscacheutil -s h --description 'Lists the options for calling dscacheutil.'
complete -c dscacheutil -s q --description 'Initiate a query using standard calls.'
complete -c dscacheutil -s a --description 'Optional flag to q for a specific key with a value.'
complete -c dscacheutil -o cachedump --description 'Dumps an overview of the cache by default.'
complete -c dscacheutil -o buckets --description 'Used in conjunction with cachedump to also print hash bucket usage of the cur…'
complete -c dscacheutil -o entries --description 'Used in conjunction with cachedump to dump detailed information about cache e…'
complete -c dscacheutil -o configuration --description 'Prints current configuration information, such as the search policy from Dire…'
complete -c dscacheutil -o flushcache --description 'Flushes the entire cache.   This should only be used in extreme cases.'
complete -c dscacheutil -o statistics --description 'Prints statistics from the cache including an overview and detailed call stat…'

