# dsimport
# Autogenerated from man page /usr/share/man/man1/dsimport.1
complete -c dsimport -l crypt --description 'is used to signify that all user passwords are crypt-based.'
complete -c dsimport -l force --description 'forces a specific value for the named attribute for all records during the im…'
complete -c dsimport -l groupid --description 'is the GID used for any records that do not specify a primary GID.'
complete -c dsimport -l grouppreset --description 'designate a preset record to be applied to imported group records.'
complete -c dsimport -l loglevel --description 'changes the amount of logging detail output to the log file.'
complete -c dsimport -l outputfile --description 'Outputs a plist to the specified file with a list of changed users or groups …'
complete -c dsimport -l password --description 'is the admin\'s password for import operations.'
complete -c dsimport -l recordformat --description 'passes in the delimiters and attributes and record type to specify the order …'
complete -c dsimport -l recordtype --description 'Override the record type defined in the import file.'
complete -c dsimport -l remotehost --description 'connects to a remote host at the network address specified.'
complete -c dsimport -l remoteusername --description 'specifies user name to use for the remote connection.'
complete -c dsimport -l remotepassword --description 'specifies password to use for the remote connection.'
complete -c dsimport -l startid --description 'indicates the ID number to start with when the import tool generates user or …'
complete -c dsimport -l template --description 'is used for delimited import of files that lack field descriptions.'
complete -c dsimport -l username --description 'is the admin username to use when importing records.'
complete -c dsimport -l userpreset --description 'designate a preset record to be applied to imported user records.'

