# dsymutil
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/dsymutil.1
complete -c dsymutil -o arch --description 'Link DWARF debug information only for specified CPU architecture types.'
complete -c dsymutil -s f -l flat --description 'Produce a flat dSYM file.  A â.'
complete -c dsymutil -s o -l out --description 'Specifies an alternate path to place the . dSYM bundle.'
complete -c dsymutil -l oso-prepend-path --description 'Specifies a path to prepend to all debug symbol object file paths.'
complete -c dsymutil -s s -l symtab --description 'Dumps the symbol table found in executable or object file(s) and exits.'
complete -c dsymutil -s t -l threads --description 'Specifies the maximum number (n) of simultaneous threads to use when linking …'
complete -c dsymutil -s v -l version --description 'Display the current version of dsymutil.'
complete -c dsymutil -l verbose --description 'Display verbose information when linking.'
complete -c dsymutil -s u -l update --description 'Update an existing dSYM file to contain the latest accelerator tables and oth…'
complete -c dsymutil -l minimize --description 'When used when creating a dSYM file, this option will suppress the emission o…'
complete -c dsymutil -l symbol-map --description 'Either pass a . bcsymbolmap file or a directory containing the collection of .'
complete -c dsymutil -l dump-debug-map --description 'Dump the executable debug-map (the list of the object files containing the de…'
complete -c dsymutil -s y --description 'Treat exe_file as a YAML debug-map rather than an executable.'

