# emlog
# Autogenerated from man page /usr/share/man/man8/emlog.pl.8
complete -c emlog -s p --description 'Tells emlog to listen on the given local port number, processing the UDP pack…'
complete -c emlog -s l --description 'Tells emlog to process a single line of text then quit.'

