# env
# Autogenerated from man page /usr/share/man/man1/env.1
complete -c env -s i --description 'Execute the utility with only those environment variables specified by name N…'
complete -c env -s P --description 'Search the set of directories as specified by altpath to locate the specified…'
complete -c env -s S --description 'Split apart the given string into multiple strings, and process each of the r…'
complete -c env -s u --description 'If the environment variable name is in the environment, then remove it before…'
complete -c env -s v --description 'Print verbose information for each step of processing done by the env utility.'

