# extcheck
# Autogenerated from man page /usr/share/man/man1/extcheck.1
complete -c extcheck -o verbose --description 'Lists  jar files in the extension directory as they are checked.'
complete -c extcheck -s J --description 'Pass option to the Java virtual machine, where  option is one of the options …'
complete -c extcheck -o J-Xms48m --description 'sets the startup memory to 48 megabytes.   SEE ALSO jar (1).'

