# filtercalltree
# Autogenerated from man page /usr/share/man/man1/filtercalltree.1
complete -c filtercalltree -o invertCallTree --description 'Print the call tree from hottest to coldest stack frame.'
complete -c filtercalltree -o pruneCount --description 'Remove branches of the call tree that have count less than count.'
complete -c filtercalltree -o pruneMallocSize --description 'Remove branches of the call tree that have malloc size less than size, such a…'
complete -c filtercalltree -o chargeSystemLibraries --description 'Remove stack frames from all libraries in /System and /usr, while still charg…'
complete -c filtercalltree -o chargeLibrary --description 'Remove stack frames from library-name, while still charging their cost to the…'
complete -c filtercalltree -o keepBoundaries --description 'When charging libraries to callers, keep the top call into excluded libraries.'

