# find
# Autogenerated from man page /usr/share/man/man1/find.1
complete -c find -s E --description 'Interpret regular expressions followed by -regex and -iregex primaries as ext…'
complete -c find -s H --description 'Cause the file information and file type (see stat 2 ) returned for each symb…'
complete -c find -s L --description 'Cause the file information and file type (see stat 2 ) returned for each symb…'
complete -c find -s P --description 'Cause the file information and file type (see stat 2 ) returned for each symb…'
complete -c find -s X --description 'Permit find to be safely used in conjunction with xargs 1.'
complete -c find -s d --description 'Cause find to perform a depth-first traversal, i. e.'
complete -c find -s f --description 'Specify a file hierarchy for find to traverse.'
complete -c find -s s --description 'Cause find to traverse the file hierarchies in lexicographical order, i. e.'
complete -c find -s x --description 'Prevent find from descending into directories that have a device number diffe…'

