# finger
# Autogenerated from man page /usr/share/man/man1/finger.1
complete -c finger -s 4 --description 'Forces finger to use IPv4 addresses only.'
complete -c finger -s 6 --description 'Forces finger to use IPv6 addresses only.'
complete -c finger -s g --description 'This option restricts the gecos output to only the users\' real name.'
complete -c finger -s h --description 'When used in conjunction with the s option, the name of the remote host is di…'
complete -c finger -s k --description 'Disable all use of utmpx 5.'
complete -c finger -s l --description 'Produce a multi-line format displaying all of the information described for t…'
complete -c finger -s m --description 'Prevent matching of user names.'
complete -c finger -s o --description 'When used in conjunction with the s option, the office location and office ph…'
complete -c finger -s p --description 'Prevent the l option of finger from displaying the contents of the .'
complete -c finger -s s --description 'Display the user\'s login name, real name, terminal name and write status (as …'

