# fmt
# Autogenerated from man page /usr/share/man/man1/fmt.1
complete -c fmt -s c --description 'Center the text, line by line.'
complete -c fmt -s m --description 'Try to format mail header lines contained in the input sensibly.'
complete -c fmt -s n --description 'Format lines beginning with a \\&.  (dot) character.'
complete -c fmt -s p --description 'Allow indented paragraphs.'
complete -c fmt -s s --description 'Collapse whitespace inside lines, so that multiple whitespace characters are …'
complete -c fmt -s d --description 'Treat the chars (and no others) as sentence-ending characters.'
complete -c fmt -s l --description 'Replace multiple spaces with tabs at the start of each output line, if possib…'
complete -c fmt -s t --description 'Assume that the input files\' tabs assume number spaces per tab stop.'

