# fold
# Autogenerated from man page /usr/share/man/man1/fold.1
complete -c fold -s b --description 'Count width in bytes rather than column positions.'
complete -c fold -s s --description 'Fold line after the last blank character within the first width column positi…'
complete -c fold -s w --description 'Specify a line width to use instead of the default 80 columns.'

