# fs_usage
# Autogenerated from man page /usr/share/man/man1/fs_usage.1
complete -c fs_usage -s e --description 'Specifying the e option generates output that excludes sampling of the runnin…'
complete -c fs_usage -s w --description 'Specifying the w option forces a wider, more detailed output, regardless of t…'
complete -c fs_usage -s f --description 'Specifying the f option turns on output filtering based on the mode provided.'
complete -c fs_usage -s b --description 'Specifying the b option annotates disk I/O events with BootCache info (if ava…'
complete -c fs_usage -s t --description 'Specifies a run timeout in seconds.'
complete -c fs_usage -s R --description 'Specifies a raw trace file to process.'
complete -c fs_usage -s S --description 'If R is selected, specifies the start time in microseconds to begin processin…'
complete -c fs_usage -s E --description 'If R is selected, specifies the ending time in microseconds to stop processin…'

