# fsck_cs
# Autogenerated from man page /usr/share/man/man8/fsck_cs.8
complete -c fsck_cs -s q --description 'Performs a "quick" check and indicates if any corruptions were found via the …'
complete -c fsck_cs -s p --description 'Operates in "preen" mode.   MLV mirror blocks are repaired where necessary.'
complete -c fsck_cs -s y --description 'Causes fsck_cs to assume "yes" as the answer to all questions.'
complete -c fsck_cs -s n --description 'Causes fsck_cs to assume "no" as the answer to all questions.'
complete -c fsck_cs -s x --description 'Causes fsck_cs to produce its output in an XML-like (plist) format.'
complete -c fsck_cs -s g --description 'Causes fsck_cs to produce its output in GUI-compatible form.'
complete -c fsck_cs -s l --description 'Reproduce all console output, as well as additional status and error messages…'
complete -c fsck_cs -l pv --description 'the component CoreStorage physical volume(s) directly.'
complete -c fsck_cs -l uuid --description 'the CoreStorage logical volume group (as a UUID).'
complete -c fsck_cs -l lv --description 'a CoreStorage logical volume (as a device name) El DIAGNOSTICS The fsck_cs ut…'

