# fsck_apfs
# Autogenerated from man page /usr/share/man/man8/fsck_apfs.8
complete -c fsck_apfs -s l --description 'Enable live verification mode.'
complete -c fsck_apfs -s q --description 'Causes fsck_apfs to quickly check whether the volume is `clean\'.'
complete -c fsck_apfs -s n --description 'Never attempt to repair any damage that is found.'
complete -c fsck_apfs -s y --description 'Always attempt to repair any damage that is found.'

