# fsck_exfat
# Autogenerated from man page /usr/share/man/man8/fsck_exfat.8
complete -c fsck_exfat -s q --description 'Causes fsck_exfat to quickly check whether the volume was unmounted cleanly.'
complete -c fsck_exfat -s f --description 'This option is ignored by fsck_exfat and is present only for compatibility wi…'
complete -c fsck_exfat -s p --description 'Preen the specified file systems.'
complete -c fsck_exfat -s y --description 'Causes fsck_exfat to assume yes as the answer to all questions.'
complete -c fsck_exfat -s n --description 'Causes fsck_exfat to assume no as the answer to all questions.'
complete -c fsck_exfat -s g --description 'Causes fsck_exfat to produce its output in GUI-compatible form.'
complete -c fsck_exfat -s x --description 'Causes fsck_exfat to produce its output in an XML-like form.'
complete -c fsck_exfat -s d --description 'Causes fsck_exfat to produce extra debugging output.'

