# ftp-proxy
# Autogenerated from man page /usr/share/man/man8/ftp-proxy.8
complete -c ftp-proxy -s A --description 'Permit only anonymous FTP connections.'
complete -c ftp-proxy -s a --description 'Specify the local IP address to use in bind 2 as the source for connections m…'
complete -c ftp-proxy -s D --description 'Specify a debug level, where the proxy emits verbose debug output into syslog…'
complete -c ftp-proxy -s g --description 'Specify the named group to drop group privileges to, after doing pf 4 lookups…'
complete -c ftp-proxy -s i --description 'Set ftp-proxy ftp-proxy for use with IP-Filter.'
complete -c ftp-proxy -s M --description 'Specify the upper end of the port range the proxy will use for the data conne…'
complete -c ftp-proxy -s m --description 'Specify the lower end of the port range the proxy will use for all data conne…'
complete -c ftp-proxy -s n --description 'Activate network address translation NAT mode.'
complete -c ftp-proxy -s p --description 'Set ftp-proxy ftp-proxy for use with pf.'
complete -c ftp-proxy -s R --description 'Reverse proxy mode for FTP servers running behind a NAT gateway.'
complete -c ftp-proxy -s r --description 'Use reverse host reverse DNS lookups for logging and libwrap use.'
complete -c ftp-proxy -s S --description 'Source address to use for data connections made by the proxy.'
complete -c ftp-proxy -s t --description 'Specifies a timeout, in seconds.'
complete -c ftp-proxy -s u --description 'Specify the named user to drop privilege to, after doing pf 4 lookups which r…'
complete -c ftp-proxy -s V --description 'Be verbose.'
complete -c ftp-proxy -s w --description 'Use the tcp wrapper access control library hosts_access 3, allowing connectio…'

