# fwkdp
# Autogenerated from man page /usr/share/man/man1/fwkdp.1
complete -c fwkdp -l setargs --description 'Sets the nvram boot-args on the current machine to boot-args Ns \\&.'
complete -c fwkdp -l proxy --description 'Use proxy mode only.'
complete -c fwkdp -l core --description 'Use core dump receive mode only.'
complete -c fwkdp -l verbose --description 'Verbose mode.'
complete -c fwkdp -l disable --description 'Sets the nvram boot-args on the current machine to "debug=0x146" which disabl…'
complete -c fwkdp -l erase --description 'Deletes the boot-args variable from nvram.'
complete -c fwkdp -l ioff --description 'Turns off interactive mode.'
complete -c fwkdp -l restart --description 'Automatically restarts the machine only after the nvram has been modified by …'
complete -c fwkdp -l help --description 'Displays usage info for fwkdp.'

