# fwkpfv
# Autogenerated from man page /usr/share/man/man1/fwkpfv.1
complete -c fwkpfv -l appendlog --description 'Append output logging to /tmp/fwkpf. log.'
complete -c fwkpfv -l openlog --description 'Open log file with Console. app.  Only valid with a Ns \\&.'
complete -c fwkpfv -l newlog --description 'Create a new log file, rather than append.  Only valid with a Ns \\&.'
complete -c fwkpfv -l prefix --description 'Prefix logger machine\'s ID to each log.'
complete -c fwkpfv -l publish --description 'Do not publish FireWire unit directory keys.'
complete -c fwkpfv -l single --description 'Use a single window even if multiple loggers are present.'
complete -c fwkpfv -l buffer --description 'Sets the host\'s psuedo address space queue buffer to size Ns in bytes.'
complete -c fwkpfv -l file --description 'Sets the log file path, if in use, to path Ns given as a path to a file.'
complete -c fwkpfv -l setargs --description 'Sets the nvram boot-args on the current machine to boot-args Ns \\&.'
complete -c fwkpfv -l setpm --description 'Sets the nvram boot-args on the current machine to "debug=0x14e io=0x880".'
complete -c fwkpfv -l disable --description 'Sets the nvram boot-args on the current machine to "debug=0x146" which disabl…'
complete -c fwkpfv -l erase --description 'Deletes the boot-args variable from nvram.'
complete -c fwkpfv -l ioff --description 'Turns off interactive mode.'
complete -c fwkpfv -l restart --description 'Automatically restarts the machine only after the nvram has been modified by …'
complete -c fwkpfv -l help --description 'Displays usage info for fwkpfv.'

