# gcore
# Autogenerated from man page /usr/share/man/man1/gcore.1
complete -c gcore -s s --description 'Suspend the process while the core file is captured.'
complete -c gcore -s v --description 'Report progress on the dump as it proceeds.'
complete -c gcore -s b --description 'Limit the size of the core file to size MiBytes.'
complete -c gcore -s o --description 'Write the core file to path.'
complete -c gcore -s c --description 'Write the core file to pathformat.'

