# GetFileInfo
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/GetFileInfo.1
complete -c GetFileInfo -s P --description 'Acts on a symlink file instead of the file the symlink resolves to.'
complete -c GetFileInfo -s a --description 'Gets a file\'s attribute bits where <attribute-letter> is one of the following…'
complete -c GetFileInfo -s t --description 'Gets the file type, a string of exactly four characters.'
complete -c GetFileInfo -s c --description 'Gets the file\'s creator, a string of four characters enclosed in quotation ma…'
complete -c GetFileInfo -s d --description 'Gets the creation date, a string of the form "mm/dd/yyyy hh:mm:ss" in 24-hour…'
complete -c GetFileInfo -s m --description 'Gets the modification date, a string of the form "mm/dd/yyyy hh:mm:ss" in 24-…'

