# git-quiltimport
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-quiltimport.1
complete -c git-quiltimport -s n -l dry-run --description 'Walk through the patches in the series and warn if we cannot find all of the …'
complete -c git-quiltimport -l author --description 'The author name and email address to use when no author information can be fo…'
complete -c git-quiltimport -l patches --description 'The directory to find the quilt patches.'
complete -c git-quiltimport -l series --description 'The quilt series file.'

