# git-credential-store
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-credential-store.1
complete -c git-credential-store -l file --description 'Use <path> to lookup and store credentials.'

