# git-upload-pack
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-upload-pack.1
complete -c git-upload-pack -l strict --description '.'
complete -c git-upload-pack -l timeout --description '.'
complete -c git-upload-pack -l stateless-rpc --description '.'
complete -c git-upload-pack -l advertise-refs --description '.'

