# git-cherry
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/git-cherry.1
complete -c git-cherry -s v --description 'Show the commit subjects next to the SHA1s.'

