# groff
# Autogenerated from man page /usr/share/man/man1/groff.1
complete -c groff -s p --description 'and.'
complete -c groff -s l --description 'See groff_font (5) and the man pages of the output devices for more details.'
complete -c groff -s P --description 'to pass options to output devices; for example, the following selects A4 pape…'

