# h2ph5
# Autogenerated from man page /usr/share/man/man1/h2ph5.18.1
complete -c h2ph5 -s d --description 'Put the resulting .'
complete -c h2ph5 -s r --description 'Run recursively; if any of headerfiles are directories, then run h2ph on all …'
complete -c h2ph5 -s a --description 'Run automagically; convert headerfiles, as well as any .'
complete -c h2ph5 -s l --description 'Symbolic links will be replicated in the destination directory.'
complete -c h2ph5 -s h --description 'Put \'hints\' in the . ph files which will help in locating problems with h2ph.'
complete -c h2ph5 -s D --description 'Include the code from the . h file as a comment in the . ph file.'

