# hdik
# Autogenerated from man page /usr/share/man/man8/hdik.8
complete -c hdik -o shadow --description 'Use a shadow file in conjunction with the data in the image.'
complete -c hdik -o nomount --description 'Suppress automatic mounting of filesystems contained within the image.'
complete -c hdik -o drivekey --description 'Specify a key/value pair for the IOHDIXHDDrive object created (shows up in th…'

