# heap
# Autogenerated from man page /usr/share/man/man1/heap.1
complete -c heap -s s --description 'Sort output by total size of class instances, rather than by count.'
complete -c heap -o guessNonObjects --description 'Look through the memory contents of each Objective-C object to find pointers …'
complete -c heap -o sumObjectFields --description 'Do the same analysis as with the guessNonObjects option, but add the sizes of…'
complete -c heap -o showSizes --description 'Show the distribution of each malloc size for each object, instead of summing…'
complete -c heap -o addresses --description 'Print the addresses of all malloc blocks found on the heap in ascending addre…'
complete -c heap -o noContent --description 'Do not show object content in -addresses mode.'

