# hfs
# Autogenerated from man page /usr/share/man/man8/hfs.util.8
complete -c hfs -s a --description 'Adopt permissions for the HFS file system at device.'
complete -c hfs -s I --description 'Print out status information about the journal on the HFS file system at moun…'
complete -c hfs -s J --description 'Enable journaling on the HFS file system mounted on mountpoint.'
complete -c hfs -s k --description 'Get the UUID key for the HFS file system at device.'
complete -c hfs -s m --description 'Mount the HFS file system located on device onto mountpoint with the flags mo…'
complete -c hfs -s M --description 'Force mount the HFS file system located on device onto mountpoint with the fl…'
complete -c hfs -s N --description 'Disable journaling on a HFS+ file system located at device.'
complete -c hfs -s p --description 'Probe the device for an HFS file system using the flags mountflag1 mountflag2…'
complete -c hfs -s s --description 'Set the UUID key (generates a new UUID value) for the HFS file system at devi…'
complete -c hfs -s u --description 'Unmount the HFS file system located at device.'
complete -c hfs -s U --description 'Disable journaling on the HFS+ file system mounted on mountpoint El Pp The mo…'

