# ifconfig
# Autogenerated from man page /usr/share/man/man8/ifconfig.8
complete -c ifconfig -o alias --description 'Remove the network address specified.'
complete -c ifconfig -o arp --description 'Disable the use of the Address Resolution Protocol arp 4.'
complete -c ifconfig -o debug --description 'Disable driver dependent debugging code.'
complete -c ifconfig -o mediaopt --description 'If the driver supports the media selection system, disable the specified medi…'
complete -c ifconfig -o rxcsum --description 'If the driver supports user-configurable checksum offloading, disable receive…'
complete -c ifconfig -o tso --description 'If the driver supports tcp 4 segmentation offloading, disable TSO on the inte…'
complete -c ifconfig -o lro --description 'If the driver supports tcp 4 large receive offloading, disable LRO on the int…'
complete -c ifconfig -o av --description 'If supported by the driver, disable 802. 1 AVB on the interface.'
complete -c ifconfig -o vlanmtu --description 'If the driver offers user-configurable VLAN support, disable reception of ext…'
complete -c ifconfig -o link --description 'on Disable special processing at the link level with the specified interface.'
complete -c ifconfig -o bonddev --description 'If the interface is a bond pseudo device, disassociate the physical interface…'
complete -c ifconfig -o tunnel --description 'Unconfigure the physical source and destination address for IP tunnel interfa…'
complete -c ifconfig -o vlandev --description 'If the driver is a vlan 4 pseudo device, disassociate the parent interface fr…'

