# ioreg
# Autogenerated from man page /usr/share/man/man8/ioreg.8
complete -c ioreg -s a --description 'Archive the output in XML.'
complete -c ioreg -s b --description 'Show the object name in bold.'
complete -c ioreg -s c --description 'Show the object properties only if the object is an instance of, or derives f…'
complete -c ioreg -s d --description 'Limit tree traversal to the specified depth.'
complete -c ioreg -s f --description 'Enable smart formatting.'
complete -c ioreg -s i --description 'Show the object inheritance.'
complete -c ioreg -s k --description 'Show the object properties only if the object has the specified key.'
complete -c ioreg -s l --description 'Show properties for all displayed objects.'
complete -c ioreg -s n --description 'Show the object properties only if the object has the specified name.'
complete -c ioreg -s p --description 'Traverse the registry over the specified plane.'
complete -c ioreg -s r --description 'Show subtrees rooted by objects that match the specified criteria.'
complete -c ioreg -s t --description 'Show tree location of each subtree.'
complete -c ioreg -s w --description 'Clip the output to the specified line width.'
complete -c ioreg -s x --description 'Show data and numbers as hexadecimal.  El.'

