# ipcrm
# Autogenerated from man page /usr/share/man/man1/ipcrm.1
complete -c ipcrm -s M --description 'Mark the shared memory segment associated with key ipcrm shmkey for removal.'
complete -c ipcrm -s m --description 'Mark the shared memory segment associated with id ipcrm shmid for removal.'
complete -c ipcrm -s Q --description 'Remove the message queue associated with key ipcrm msgkey from the system.'
complete -c ipcrm -s q --description 'Remove the message queue associated with the id ipcrm msqid from the system.'
complete -c ipcrm -s S --description 'Remove the semaphore set associated with key ipcrm semkey from the system.'
complete -c ipcrm -s s --description 'Removes the semaphore set associated with id ipcrm semid from the system.'

