# ipcs
# Autogenerated from man page /usr/share/man/man1/ipcs.1
complete -c ipcs -s a --description 'Show the maximum amount of information possible when displaying active semaph…'
complete -c ipcs -s b --description 'Show the maximum allowed sizes for active semaphores, message queues, and sha…'
complete -c ipcs -s c --description 'Show the creator\'s name and group for active semaphores, message queues, and …'
complete -c ipcs -s M --description 'Display system information about shared memory.'
complete -c ipcs -s m --description 'Display information about active shared memory segments.'
complete -c ipcs -s o --description 'Show outstanding usage for active message queues, and shared memory segments.'
complete -c ipcs -s p --description 'Show the process ID information for active semaphores, message queues, and sh…'
complete -c ipcs -s Q --description 'Display system information about messages queues.'
complete -c ipcs -s q --description 'Display information about active message queues.'
complete -c ipcs -s S --description 'Display system information about semaphores.'
complete -c ipcs -s s --description 'Display information about active semaphores.'
complete -c ipcs -s T --description 'Display system information about shared memory, message queues and semaphores.'
complete -c ipcs -s t --description 'Show access times for active semaphores, message queues, and shared memory se…'

