# jar
# Autogenerated from man page /usr/share/man/man1/jar.1
complete -c jar -s C --description 'Temporarily changes directories (cd dir) during  execution of the jar command…'
complete -c jar -o J-Xms48m --description 'sets the startup memory to 48 megabytes.  It is a common convention for.'
complete -c jar -s J --description 'to pass options to the underlying virtual machine.'

