# jdb
# Autogenerated from man page /usr/share/man/man1/jdb.1
complete -c jdb -o sourcepath --description 'Uses the given path in searching for source files in the specified path.'
complete -c jdb -o attach --description 'Attaches the debugger to previously running VM using the default connection m…'
complete -c jdb -o launch --description 'Launches the debugged application immediately upon startup of  jdb .'
complete -c jdb -o Xrunjdwp:transport --description 'server=y,suspend=n T}	T{.'
complete -c jdb -s D --description '.'
complete -c jdb -o classpath --description 'and.'
complete -c jdb -s X --description '.'
complete -c jdb -s J --description 'Pass option to the Java virtual machine, where  option is one of the options …'
complete -c jdb -o J-Xms48m --description 'sets the startup memory to 48 megabytes.  It is a common convention for.'

