# jmap
# Autogenerated from man page /usr/share/man/man1/jmap.1
complete -c jmap -o heap --description 'Prints a heap summary.'
complete -c jmap -o histo --description 'Prints a histogram of the heap.'
complete -c jmap -o permstat --description 'Prints class loader wise statistics of permanent  generation of Java heap.'
complete -c jmap -s h --description 'Prints a help message. if t.'
complete -c jmap -o help --description 'Prints a help message.  SEE ALSO pmap (1) jps (1) jsadebugd (1).'

