# join
# Autogenerated from man page /usr/share/man/man1/join.1
complete -c join -s a --description 'In addition to the default output, produce a line for each unpairable line in…'
complete -c join -s e --description 'Replace empty output fields with string.'
complete -c join -s o --description 'The o option specifies the fields that will be output from each file for each…'
complete -c join -s t --description 'Use character char as a field delimiter for both input and output.'
complete -c join -s v --description 'Do not display the default output, but display a line for each unpairable lin…'
complete -c join -s 1 --description 'Join on the field Ns \'th field of file 1.'
complete -c join -s 2 --description 'Join on the field Ns \'th field of file 2.'
complete -c join -o j1 --description 'Join on the field Ns \'th field of file 1.'
complete -c join -o j2 --description 'Join on the field Ns \'th field of file 2.'
complete -c join -s j --description 'Join on the field Ns \'th field of both file 1 and file 2.'

