# jstatd
# Autogenerated from man page /usr/share/man/man1/jstatd.1
complete -c jstatd -o nr --description 'Do not attempt to create an internal RMI registry within the  jstatd process …'
complete -c jstatd -s p --description 'Port number where the RMI registry is expected to be found, or,  if not found…'
complete -c jstatd -s n --description 'Name to which the remote RMI object is bound in the RMI registry.'
complete -c jstatd -s J --description 'Pass option to the java launcher called by javac.'

