# jstack
# Autogenerated from man page /usr/share/man/man1/jstack.1
complete -c jstack -s m --description 'prints mixed mode (both Java and native C/C++ frames) stack trace. if t.'
complete -c jstack -s h --description 'Prints a help message. if t.'
complete -c jstack -o help --description 'Prints a help message.'

