# kdc
# Autogenerated from man page /usr/share/man/man8/kdc.8
complete -c kdc -s c --description 'Specifies the location of the config file, the default is /var/heimdal/kdc.'
complete -c kdc -s p --description 'Turn off the requirement for pre-autentication in the initial AS-REQ for all …'
complete -c kdc -l max-request --description 'Gives an upper limit on the size of the requests that the kdc is willing to h…'
complete -c kdc -s H --description 'Makes the kdc listen on port 80 and handle requests encapsulated in HTTP.'
complete -c kdc -l no-524 --description 'don\'t respond to 524 requests.'
complete -c kdc -l kerberos4 --description 'respond to Kerberos 4 requests.'
complete -c kdc -l kerberos4-cross-realm --description 'respond to Kerberos 4 requests from foreign realms.'
complete -c kdc -s r --description 'What realm this server should act as when dealing with version 4 requests.'
complete -c kdc -s K --description 'Enable kaserver emulation (in case it\'s compiled in).'
complete -c kdc -s P --description 'Specifies the set of ports the KDC should listen on.'
complete -c kdc -l addresses --description 'The list of addresses to listen for requests on.'
complete -c kdc -l detach --description 'detach from pty and run as a daemon.'
complete -c kdc -l disable-des --description 'disable add des encryption types, makes the kdc not use them.'

