# kdcsetup
# Autogenerated from man page /usr/share/man/man8/kdcsetup.8
complete -c kdcsetup -s v --description 'Controls the amount of output generated by kdcsetup.'
complete -c kdcsetup -s a --description 'Name of a directory administrator authorized to make changes in Open Director…'
complete -c kdcsetup -s p --description 'The password for the above admin.   Required parameter.'

