# kextunload
# Autogenerated from man page /usr/share/man/man8/kextunload.8
complete -c kextunload -s b --description 'Unload executable and IOKitPersonalities (as described immediately above) for…'
complete -c kextunload -s c --description 'Terminate all instances of class classname that are in the IOService plane of…'
complete -c kextunload -s h --description 'Print a help message describing each option flag and exit with a success resu…'
complete -c kextunload -s m --description 'Same as b (remains for backward compatibility).'
complete -c kextunload -s p --description 'Terminate services and remove personalities only; do not unload kexts.'
complete -c kextunload -s q --description 'Quiet mode; print no informational or error messages.'
complete -c kextunload -s v --description 'Verbose mode; print information about program operation.'

