# kextstat
# Autogenerated from man page /usr/share/man/man8/kextstat.8
complete -c kextstat -s a --description 'Print the architecture of the kext.'
complete -c kextstat -s b --description 'Display the status of only the kext with the given bundle identifier.'
complete -c kextstat -s h --description 'Print a help message describing each option flag and exit with a success resu…'
complete -c kextstat -s k --description 'Don\'t show information for built-in components of the kernel.'
complete -c kextstat -s l --description 'Print the list of loaded kexts only and omit the header (useful for running o…'
complete -c kextstat -s s --description 'Sort the list by load address.'

