# kextlibs
# Autogenerated from man page /usr/share/man/man8/kextlibs.8
complete -c kextlibs -s h --description 'Print a help message describing each option flag and exit with a success resu…'
complete -c kextlibs -o all-symbols --description 'Print reports on all symbols that remain undefined, all symbols that have bee…'
complete -c kextlibs -s c --description 'Print the compatible version rather than the current version.'
complete -c kextlibs -o multdef-symbols --description 'Print all undefined symbols from kext found in more than one library kext, fo…'
complete -c kextlibs -o non-kpi --description 'Search the compatibility kext, com. apple. kernel. 6.'
complete -c kextlibs -o onedef-symbols --description 'Print all undefined symbols from kext found in exactly one library kext, foll…'
complete -c kextlibs -s r --description 'Search directory for dependencies.'
complete -c kextlibs -s e --description 'Add /System/Library/Extensions and /Library/Extensions to the list of directo…'
complete -c kextlibs -o undef-symbols --description 'Print all undefined symbols from kext that can\'t be found in any library kext…'
complete -c kextlibs -o unsupported --description 'Search unsupported library kexts for symbols (by default they are not searche…'
complete -c kextlibs -s v --description 'Verbose mode; print information about program operation.'
complete -c kextlibs -o xml --description 'Print an XML fragment to stdout suitable for copying and pasting directly int…'

