# kill
# Autogenerated from man page /usr/share/man/man1/kill.1
complete -c kill -s s --description 'A symbolic signal name specifying the signal to be sent instead of the defaul…'
complete -c kill -s l --description 'If no operand is given, list the signal names; otherwise, write the signal na…'
complete -c kill -o signal_name --description 'A symbolic signal name specifying the signal to be sent instead of the defaul…'
complete -c kill -o signal_number --description 'A non-negative decimal integer, specifying the signal to be sent instead of t…'

