# kpasswdd
# Autogenerated from man page /usr/share/man/man8/kpasswdd.8
complete -c kpasswdd -l addresses --description 'For each till the argument is given, add the address to what kpasswdd should …'
complete -c kpasswdd -l check-library --description 'If your system has support for dynamic loading of shared libraries, you can u…'
complete -c kpasswdd -l check-function --description 'This is the function to call in the loaded library.'
complete -c kpasswdd -s k --description 'Keytab to get authentication key from.'
complete -c kpasswdd -s r --description 'Default realm.'
complete -c kpasswdd -s p --description 'Port to listen on (default service kpasswd - 464).'

