# krb5-config
# Autogenerated from man page /usr/share/man/man1/krb5-config.1
complete -c krb5-config -l prefix --description 'Print the prefix if no dir is specified, otherwise set prefix to dir.'
complete -c krb5-config -l exec-prefix --description 'Print the exec-prefix if no dir is specified, otherwise set exec-prefix to di…'
complete -c krb5-config -l libs --description 'Output the set of libraries that should be linked against.'
complete -c krb5-config -l cflags --description 'Output the set of flags to give to the C compiler when using the Heimdal libr…'

