# krbservicesetup
# Autogenerated from man page /usr/share/man/man8/krbservicesetup.8
complete -c krbservicesetup -s x --description 'Use kadmin. local instead of kadmin.'
complete -c krbservicesetup -s r --description 'The Kerberos realm of the server.'
complete -c krbservicesetup -s a --description 'Name of an administrator with priveleges to add principals to the KDC.'
complete -c krbservicesetup -s p --description 'Password for the above user.'
complete -c krbservicesetup -s t --description 'The path of the keytab file to write.'
complete -c krbservicesetup -s f --description 'The path of the plist file containing the list of services to be configured s…'

