# latency
# Autogenerated from man page /usr/share/man/man1/latency.1
complete -c latency -s c --description 'When the c option is specified, it takes a path to a code file that contains …'
complete -c latency -s h --description 'Display high resolution interrupt latencies and write them to latencies.'
complete -c latency -s m --description 'Display per-CPU interrupt latency statistics.'
complete -c latency -o it --description 'Set the interrupt latency threshold, expressed in microseconds.'
complete -c latency -s l --description 'Specifies a log file that is written to when either the interrupt or scheduli…'
complete -c latency -s n --description 'By default, latency latency acts on the default /System/Library/Kernels/kerne…'
complete -c latency -s p --description 'Specifies the priority level to observe scheduler latencies for.'
complete -c latency -o st --description 'Set the scheduler latency threshold in microseconds.'
complete -c latency -s R --description 'Specifies a raw trace file to use as input.'

