# launchctl
# Autogenerated from man page /usr/share/man/man1/launchctl.1
complete -c launchctl -s k --description 'If the service is already running, kill the running instance before restartin…'
complete -c launchctl -s p --description 'Upon success, print the PID of the new process or the already-running process…'
complete -c launchctl -s s --description 'Force the service to start.'
complete -c launchctl -s x --description 'Attach to xpcproxy 3 before it execs and becomes the service process.'
complete -c launchctl -s w --description 'Overrides the Disabled key and sets it to false or true for the load and unlo…'
complete -c launchctl -s F --description 'Force the loading or unloading of the plist.  Ignore the Disabled key.'
complete -c launchctl -s S --description 'Some jobs only make sense in certain contexts.'
complete -c launchctl -s D --description 'Load or unload all plist 5 files in the search path given.'
complete -c launchctl -s l --description 'What unique label to assign this job to launchd.'
complete -c launchctl -s o --description 'Where to send the stdout of the program.'
complete -c launchctl -s e --description 'Where to send the stderr of the program.'

