# layerutil
# Autogenerated from man page /usr/share/man/man1/layerutil.1
complete -c layerutil -s c --description 'Convert to lcr format.'
complete -c layerutil -s f --description 'Saves the flattened image as a jpeg to the output path given by the -o flag.'
complete -c layerutil -s g --description 'Sets program to use gpu optimized compression.'
complete -c layerutil -s l --description 'Set the lossy compression factor used for image content to a value between 0 …'
complete -c layerutil -s s --description 'Used to specify the scale factor used in the generated lcr file.'
complete -c layerutil -s p --description 'v can be one of srgb/p3.'
complete -c layerutil -s o --description 'Output file name.'
complete -c layerutil -s h --description 'Prints out usage information.'
complete -c layerutil -s V --description 'Prints out version information.  \\" Ends the list Pp.'

