# lipo
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/lipo.1
complete -c lipo -o info --description 'Briefly list the architecture types in the input universal file  (just the na…'
complete -c lipo -o detailed_info --description 'Display a detailed list of the architecture types in the input universal file…'
complete -c lipo -o arch --description 'Tells  lipo that  input_file contains the specified architecture type.'
complete -c lipo -o arch_blank --description 'Specifies that the output for the specified R arch_type will be an MH_DYLIB_S…'
complete -c lipo -o output --description 'Specifies its argument to be the output file.'
complete -c lipo -o create --description 'Take the input files (or file) and create one universal output file from them.'
complete -c lipo -o thin --description 'Take one input file and create a thin output file with the specified R arch_t…'
complete -c lipo -o replace --description 'Take one universal input file; in the output file, replace the  arch_type con…'
complete -c lipo -o remove --description 'Take one universal input file and remove the  arch_type from that universal f…'
complete -c lipo -o extract --description 'Take one universal input file and copy the  arch_type from that universal fil…'
complete -c lipo -o extract_family --description 'Take one universal input file and copy all of the  R arch_type s for the fami…'
complete -c lipo -o verify_arch --description 'Take one input file and verify the specified R arch_type s are present in the…'
complete -c lipo -o segalign --description 'which are used in combination with other options.'

