# llvm-profdata
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/llvm-profdata.1
complete -c llvm-profdata -o help --description 'Print a summary of command line options.'
complete -c llvm-profdata -o output -s o --description 'Specify the output file name.'
complete -c llvm-profdata -o weighted-input --description 'Specify an input file name along with a weight.'
complete -c llvm-profdata -o input-files -s f --description 'Specify a file which contains a list of files to merge.'
complete -c llvm-profdata -o instr --description 'Specify that the input profile is an instrumentation-based profile.'
complete -c llvm-profdata -o sample --description 'Specify that the input profile is a sample-based profile.'
complete -c llvm-profdata -o binary --description 'Emit the profile using a binary encoding.'
complete -c llvm-profdata -o text --description 'Emit the profile in text mode.'
complete -c llvm-profdata -o gcc --description 'Emit the profile using GCCâs gcov format (Not yet supported).'
complete -c llvm-profdata -o sparse --description 'Do not emit function records with 0 execution count.'
complete -c llvm-profdata -o num-threads -s j --description 'Use N threads to perform profile merging.'
complete -c llvm-profdata -o all-functions --description 'Print details for every function.'
complete -c llvm-profdata -o counts --description 'Print the counter values for the displayed functions.'
complete -c llvm-profdata -o function --description 'Print details for a function if the functionâs name contains the given stri…'
complete -c llvm-profdata -o topn --description 'Instruct the profile dumper to show the top n functions with the hottest basi…'
complete -c llvm-profdata -o memop-sizes --description 'Show the profiled sizes of the memory intrinsic calls for shown functions.'

