# locale
# Autogenerated from man page /usr/share/man/man1/locale.1
complete -c locale -s a --description 'Lists all public locales.'
complete -c locale -s c --description 'Lists the category name before each keyword, unless it is the same category a…'
complete -c locale -s k --description 'Displays the name of each keyword prior to its value.'
complete -c locale -s m --description 'Lists all available public charmaps.'

