# makewhatis
# Autogenerated from man page /usr/share/man/man8/makewhatis.8
complete -c makewhatis -s a --description 'Appends to the output file(s) instead of replacing them.'
complete -c makewhatis -s i --description 'Indents the description by column characters.  The default value is 24.'
complete -c makewhatis -s n --description 'Uses name instead of whatis.'
complete -c makewhatis -s o --description 'Outputs all lines to the file instead of */man/whatis.'
complete -c makewhatis -s v --description 'Makes makewhatis more verbose about what it is doing.'
complete -c makewhatis -s L --description 'Process only localized subdirectories corresponding to the locale specified i…'

