# malloc_history
# Autogenerated from man page /usr/share/man/man1/malloc_history.1
complete -c malloc_history -o showContent --description 'Show the content of malloc blocks of various types, including C strings, Pasc…'
complete -c malloc_history -o invert --description 'Invert the call tree, so that malloc (and the allocated content, if the showC…'
complete -c malloc_history -o ignoreThreads --description 'Combine the call trees for all threads into a single call tree.'
complete -c malloc_history -o collapseRecursion --description 'Collapse recursion within the call trees.'
complete -c malloc_history -o chargeSystemLibraries --description 'Remove stack frames from all libraries in /System and /usr, while still charg…'

