# mapstool
# Autogenerated from man page /usr/share/man/man1/mapstool.1
complete -c mapstool -s a --description 'Description of -a flag.'
complete -c mapstool -s b --description 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

