# matchTool
# Autogenerated from man page /usr/share/man/man1/matchTool.1
complete -c matchTool -s a --description 'Description of -a flag.'
complete -c matchTool -s b --description 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

