# mcxquery
# Autogenerated from man page /usr/share/man/man1/mcxquery.1
complete -c mcxquery -o user --description 'Specify the short name of the user record to read managed preferences from.'
complete -c mcxquery -o group --description 'Specify the short name of the group record to read managed preferences from.'
complete -c mcxquery -o computer --description 'Specify the computer record to read managed preferences from.'

