# mdfind
# Autogenerated from man page /usr/share/man/man1/mdfind.1
complete -c mdfind -s 0 --description 'Prints an ASCII NUL character after each result path.'
complete -c mdfind -o live --description 'Causes the mdfind command to provide live-updates to the number of files matc…'
complete -c mdfind -o count --description 'Causes the mdfind command to output the total number of matches, instead of t…'
complete -c mdfind -o onlyin --description 'Limit the scope of the search to the directory specified.'
complete -c mdfind -o name --description 'Searches for matching file names only.'
complete -c mdfind -o literal --description 'Force the provided query string to be taken as a literal query string, withou…'
complete -c mdfind -o interpret --description 'Force the provided query string to be interpreted as if the user had typed th…'

