# migcom
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/migcom.1
complete -c migcom -o q/-Q --description 'Omit /  emit warning messages.'
complete -c migcom -o v/-V --description 'Verbose mode ( on /  off ) will summarize types and routines as they are proc…'
complete -c migcom -o l/-L --description 'Controls (  off / on ) whether or not generated code logs RPC events to syste…'
complete -c migcom -o k/-K --description 'Controls (  on / off ) whether generated code complies with ANSI C standards.'
complete -c migcom -o s/-S --description 'Controls ( on /  off ) whether generated server-side code includes a generate…'
complete -c migcom -s i --description 'Specify User file prefix.'
complete -c migcom -o user --description 'Specify name of user-side RPC generated source file.'
complete -c migcom -o server --description 'Specify name of server-side RPC generated source file.'
complete -c migcom -o header --description 'Specify name of user-side generated header file.'
complete -c migcom -o sheader --description 'Specify name of server-side generated header file.'
complete -c migcom -o iheader --description 'Specify internal header file name.'
complete -c migcom -o dheader --description 'Specify defines generated header file.'
complete -c migcom -o maxonstack --description 'Specify maximum size of message on stack.'
complete -c migcom -o split --description 'Use split headers.'

