# mkbom
# Autogenerated from man page /usr/share/man/man8/mkbom.8
complete -c mkbom -s h --description 'print full usage.'
complete -c mkbom -s s --description 'create a simplified bom containing only file paths.'
complete -c mkbom -s i --description 'use the information in filelist, one entry per line, to construct the bom fil…'

