# mktemp
# Autogenerated from man page /usr/share/man/man1/mktemp.1
complete -c mktemp -s d --description 'Make a directory instead of a file.'
complete -c mktemp -s q --description 'Fail silently if an error occurs.'
complete -c mktemp -s t --description 'Generate a template (using the supplied prefix and TMPDIR if set) to create a…'
complete -c mktemp -s u --description 'Operate in unsafe mode.  The temp file will be unlinked before mktemp exits.'

