# mnthome
# Autogenerated from man page /usr/share/man/man1/mnthome.1
complete -c mnthome -s v --description 'Display version number.'
complete -c mnthome -s d --description 'Print debugging information.'
complete -c mnthome -s m --description 'Alternative mount point is specified with the m option followed by a path to …'
complete -c mnthome -s n --description 'Do not force the unmount of the previous mount point.'
complete -c mnthome -s b --description 'Exec the user\'s shell after mount of home.'
complete -c mnthome -s p --description 'A password may be specified with the p option followed by a password.'
complete -c mnthome -s i --description 'Display information about the AFP home mount point.'
complete -c mnthome -s u --description 'Attempt to unmount the current home directory mount.'
complete -c mnthome -s x --description 'This option must be followed by a path to an existing AFP mount point.'
complete -c mnthome -s s --description 'Skip preflight check to see if the currently mounted home directory is alread…'

