# mount
# Autogenerated from man page /usr/share/man/man8/mount.8
complete -c mount -s a --description 'All the filesystems listed via getfsent 3 are mounted.'
complete -c mount -s d --description 'Causes everything to be done except for the actual system call.'
complete -c mount -s f --description 'Forces the revocation of write access when trying to downgrade a filesystem m…'
complete -c mount -s o --description 'Options are specified with a o flag followed by a comma separated string of o…'
complete -c mount -s r --description 'Mount the file system read-only (even the super-user may not write it).'
complete -c mount -s t --description 'The argument following the t is used to indicate the file system type.'
complete -c mount -s u --description 'The u flag indicates that the status of an already mounted file system should…'
complete -c mount -s v --description 'Verbose mode.'
complete -c mount -s w --description 'Mount the file system read-write.'

