# mount_apfs
# Autogenerated from man page /usr/share/man/man8/mount_apfs.8
complete -c mount_apfs -s o --description 'Options passed to mount 2 are specified with the o option followed by a comma…'
complete -c mount_apfs -s u --description 'Set the owner of the files in the file system to user.'
complete -c mount_apfs -s g --description 'Set the group of the files in the file system to group.'
complete -c mount_apfs -s s --description 'The name of the snapshot to mount.'

