# mount_fdesc
# Autogenerated from man page /usr/share/man/man8/mount_fdesc.8
complete -c mount_fdesc -s o --description 'Options are specified with a o flag followed by a comma separated string of o…'

