# mount_afp
# Autogenerated from man page /usr/share/man/man8/mount_afp.8
complete -c mount_afp -s i --description 'Interactive mode, you are prompted for the password if you did not supply one…'
complete -c mount_afp -s s --description 'Soft mount (default).  Network errors, e. g.'
complete -c mount_afp -s k --description 'Hard mount.  Network errors, e. g.'
complete -c mount_afp -s o --description 'Options passed to mount 2 are specified with the o option followed by a comma…'

