# mount_cddafs
# Autogenerated from man page /usr/share/man/man8/mount_cddafs.8
complete -c mount_cddafs -s o --description 'Options are specified with a o flag followed by a comma separated string of o…'

