# mount_ftp
# Autogenerated from man page /usr/share/man/man8/mount_ftp.8
complete -c mount_ftp -s i --description 'Interactive mode, you are prompted for the username and password if you did n…'
complete -c mount_ftp -s o --description 'Options passed to mount 2 are specified with the o option followed by a comma…'

