# mountd
# Autogenerated from man page /usr/share/man/man8/mountd.8
complete -c mountd -s n --description '.'
complete -c mountd -s r --description 'exportsfile Ta Fl F Pa exportsfile Ta alternate exports file El Pp However, s…'

