# native2ascii
# Autogenerated from man page /usr/share/man/man1/native2ascii.1
complete -c native2ascii -o encoding --description 'Specifies the encoding name that is used by the conversion procedure.'
complete -c native2ascii -o reverse --description 'Performs the reverse operation: converts a file with Latin-1 or Unicode-encod…'
complete -c native2ascii -s J --description 'Pass option to the Java virtual machine, where  option is one of the options …'
complete -c native2ascii -o J-Xms48m --description 'sets the startup memory to 48 megabytes.  It is a common convention for.'

