# ncdestroy
# Autogenerated from man page /usr/share/man/man1/ncdestroy.1
complete -c ncdestroy -s h --description 'Print a help summary of the command and then exit.'
complete -c ncdestroy -s v --description 'Be verbose and show what file system is being operated on and any resulting e…'
complete -c ncdestroy -s P --description 'If the trailing component resolves to a symbolic link do not resolve the link…'
complete -c ncdestroy -s p --description 'For the init, set and ncdestroy ncinit commands set the principal to principa…'
complete -c ncdestroy -s F --description 'For the init, set and ncdestroy ncinit commands to not check the presence of …'

