# ncinit
# Autogenerated from man page /usr/share/man/man1/ncinit.1
complete -c ncinit -s h --description 'Print a help summary of the command and then exit.'
complete -c ncinit -s v --description 'Be verbose and show what file system is being operated on and any resulting e…'
complete -c ncinit -s P --description 'If the trailing component resolves to a symbolic link do not resolve the link…'
complete -c ncinit -s p --description 'For the init, set and ncinit ncinit commands set the principal to principal.'
complete -c ncinit -s F --description 'For the init, set and ncinit ncinit commands to not check the presence of the…'

