# nclist
# Autogenerated from man page /usr/share/man/man1/nclist.1
complete -c nclist -s h --description 'Print a help summary of the command and then exit.'
complete -c nclist -s v --description 'Be verbose and show what file system is being operated on and any resulting e…'
complete -c nclist -s P --description 'If the trailing component resolves to a symbolic link do not resolve the link…'
complete -c nclist -s p --description 'For the init, set and nclist ncinit commands set the principal to principal.'
complete -c nclist -s F --description 'For the init, set and nclist ncinit commands to not check the presence of the…'

