# ndisasm
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/ndisasm.1
complete -c ndisasm -s h --description 'Causes  ndisasm to exit immediately, after giving a summary of its invocation…'
complete -c ndisasm -s r --description 'Causes  ndisasm to exit immediately, after displaying its version number.'
complete -c ndisasm -s o --description 'Specifies the notional load address for the file.'
complete -c ndisasm -s s --description 'Manually specifies a synchronisation address, such that  ndisasm will not out…'
complete -c ndisasm -s e --description 'Specifies a number of bytes to discard from the beginning of the file before …'
complete -c ndisasm -s k --description 'Specifies that  length bytes, starting from disassembly offset R offset , sho…'
complete -c ndisasm -s a -s i --description 'Enables automatic (or intelligent) sync mode, in which  ndisasm will attempt …'
complete -c ndisasm -s b --description 'Specifies either 16-bit or 32-bit mode.  The default is 16-bit mode.'
complete -c ndisasm -s u --description 'Specifies 32-bit mode, more compactly than using `-b 32\'.'
complete -c ndisasm -s p --description 'Prefers instructions as defined by vendor in case of a conflict.'

