# netbiosd
# Autogenerated from man page /usr/share/man/man8/netbiosd.8
complete -c netbiosd -o debug --description 'The service will log extensive debug information and may perform extra diagno…'
complete -c netbiosd -o dump-packets --description 'Pretty-print all sent and received NetBIOS packets to the output log.'
complete -c netbiosd -o help --description 'Prints a usage message and exits.'
complete -c netbiosd -o max-refresh --description 'Maximum time (in seconds) between searches to refresh the workgroup list.'
complete -c netbiosd -o min-refresh --description 'Minimum time (in seconds) between searches to refresh the workgroup list.'
complete -c netbiosd -o stdout --description 'Causes netbiosd to print log messages to standard output instead of the syste…'

