# netlog
# Autogenerated from man page /usr/share/man/man1/netlog.1
complete -c netlog -s v --description 'Verbose output.'
complete -c netlog -s i --description 'Report socket statistics periodically.'
complete -c netlog -s I --description 'Used in combination with i, will make netlog exit after the specified number …'
complete -c netlog -s t --description 'Specify the type of interface.  By default, all interfaces will be monitored.'
complete -c netlog -s p --description 'Select a process for display.'
complete -c netlog -s c --description 'Print details in comma-separated values (CSV) form.'
complete -c netlog -s z --description 'Print details even if there was no data transfer on the socket El.'

