# newsyslog
# Autogenerated from man page /usr/share/man/man8/newsyslog.8
complete -c newsyslog -s f --description 'Instruct newsyslog to use config_file instead of /etc/newsyslog.'
complete -c newsyslog -s a --description 'Specify a directory into which archived log files will be written.'
complete -c newsyslog -s d --description 'Specify a directory which all log files will be relative to.'
complete -c newsyslog -s v --description 'Place newsyslog in verbose mode.'
complete -c newsyslog -s n --description 'Cause newsyslog not to trim the logs, but to print out what it would do if th…'
complete -c newsyslog -s r --description 'Remove the restriction that newsyslog must be running as root.'
complete -c newsyslog -s s --description 'Specify that newsyslog should not send any signals to any daemon processes th…'
complete -c newsyslog -s C --description 'If specified once, then newsyslog will create any log files which do not exis…'
complete -c newsyslog -s F --description 'Force newsyslog to trim the logs, even if the trim conditions have not been m…'
complete -c newsyslog -s N --description 'Do not perform any rotations.'
complete -c newsyslog -s R --description 'Specify that newsyslog should rotate a given list of files, even if trim cond…'

