# nmedit
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/nmedit.1
complete -c nmedit -s s --description 'Leave the symbol table entries for the global symbols listed in  filename glo…'
complete -c nmedit -s R --description 'Change the symbol table entries for the global symbols listed in  filename in…'
complete -c nmedit -s p --description 'Change symbols to private externs instead of static.'
complete -c nmedit -s A --description 'Leave all global absolute symbols except those with a value of zero, and save…'
complete -c nmedit -o arch --description 'Specifies the architecture,  arch_type, of the file for R nmedit (1) to proce…'
complete -c nmedit -s g --description 'option to cc (1)) for the global symbols it changes to static symbols so that…'
complete -c nmedit -s o --description 'Write the result into the file output.  SEE ALSO strip(1), ld(1), arch(3).'

