# ntfs
# Autogenerated from man page /usr/share/man/man8/ntfs.util.8
complete -c ntfs -s k --description 'Get the UUID key for the NTFS file system at device.'
complete -c ntfs -s m --description 'Mount the NTFS file system located on device onto mountpoint with the flags m…'
complete -c ntfs -s p --description 'Probe the device for an NTFS file system using the flags mountflag1 mountflag…'
complete -c ntfs -s u --description 'Unmount the NTFS file system located at device and mounted on mountpoint.'

