# ntpq
# Autogenerated from man page /usr/share/man/man1/ntpq.1
complete -c ntpq -o '\\&?' --description 'Display usage information and exit.'
complete -c ntpq -o '\\&' --description 'Pass the extended usage information through a pager.'
complete -c ntpq -s '>' --description 'Save the option state to \\fIcfgfile\\fP.'
complete -c ntpq -s '<' --description 'Load options from \\fIcfgfile\\fP.'
complete -c ntpq -o '\\-version' --description 'Output version of program and exit.'

