# ntptrace
# Autogenerated from man page /usr/share/man/man1/ntptrace.1
complete -c ntptrace -o '\\&?' --description 'Display usage information and exit.'
complete -c ntptrace -o '\\&' --description 'Pass the extended usage information through a pager.'
complete -c ntptrace -s v --description 'Output version of program and exit.'

