# open
# Autogenerated from man page /usr/share/man/man1/open.1
complete -c open -s a --description 'Specifies the application to use for opening the file.'
complete -c open -s b --description 'Specifies the bundle identifier for the application to use when opening the f…'
complete -c open -s e --description 'Causes the file to be opened with /Applications/TextEdit.'
complete -c open -s t --description 'Causes the file to be opened with the default text editor, as determined via …'
complete -c open -s f --description 'Reads input from standard input and opens the results in the default text edi…'
complete -c open -s F --description 'Opens the application "fresh," that is, without restoring windows.'
complete -c open -s W --description 'Causes open to wait until the applications it opens (or that were already ope…'
complete -c open -s R --description 'Reveals the file(s) in the Finder instead of opening them.'
complete -c open -s n --description 'Open a new instance of the application(s) even if one is already running.'
complete -c open -s g --description 'Do not bring the application to the foreground.'
complete -c open -s j --description 'Launches the app hidden.'
complete -c open -s h --description 'Searches header locations for a header whose name matches the given string an…'
complete -c open -s s --description 'For -h, partial or full SDK name to use; if supplied, only SDKs whose names c…'
complete -c open -l args --description 'All remaining arguments are passed to the opened application in the argv para…'

