# orbd
# Autogenerated from man page /usr/share/man/man1/orbd.1
complete -c orbd -o ORBInitialPort --description 'Specifies the port on which the name server should  be started.'
complete -c orbd -o port --description 'Specifies the activation port where the ORBD should be started.'
complete -c orbd -o defaultdb --description 'Specifies the base where the ORBD persistent storage directory  orb.'
complete -c orbd -o serverPollingTime --description 'Specifies how often the daemon thread checks for the health of registered ser…'
complete -c orbd -o serverStartupDelay --description 'Specifies how long the ServerManager waits before sending a location forward …'
complete -c orbd -s J --description 'Pass option to the Java virtual machine, where  option is one of the options …'
complete -c orbd -o J-Xms48m --description 'sets the startup memory to 48 megabytes.  It is a common convention for.'
complete -c orbd -o ORBInitialHost --description 'localhost since the name server is running on the same host as the Hello clie…'

