# osacompile
# Autogenerated from man page /usr/share/man/man1/osacompile.1
complete -c osacompile -s l --description 'Override the language for any plain text files.'
complete -c osacompile -s e --description 'Enter one line of a script.'
complete -c osacompile -s o --description 'Place the output in the file name.'
complete -c osacompile -s x --description 'Save the resulting script as execute-only.'
complete -c osacompile -s s --description 'Stay-open applet.'
complete -c osacompile -s u --description 'Use startup screen.'
complete -c osacompile -s a --description 'Create the applet or droplet for the specified target architecture arch.'
complete -c osacompile -s d --description 'Place the resulting script in the data fork of the output file.'
complete -c osacompile -s r --description 'Place the resulting script in the resource fork of the output file, in the sp…'
complete -c osacompile -s t --description 'Set the output file type to type, where type is a four-character code.'
complete -c osacompile -s c --description 'Set the output file creator to creator, where creator is a four-character cod…'

