# osalang
# Autogenerated from man page /usr/share/man/man1/osalang.1
complete -c osalang -s d --description 'Only print the default language.'
complete -c osalang -s l --description 'List in long format.'
complete -c osalang -s L --description 'Same as l, but also prints the description of each component after its name.'

