# pagestuff
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/pagestuff.1
complete -c pagestuff -o arch --description 'Specifies the architecture,  arch_type, of the file for R pagestuff (1) to op…'
complete -c pagestuff -s a --description 'Displays all pages.   All other arguments are ignored.'
complete -c pagestuff -s p --description 'Print a list of the sections of the specified Mach-O file, with offsets and l…'

