# passwd
# Autogenerated from man page /usr/share/man/man1/passwd.1
complete -c passwd -s i --description 'This option specifies where the password update should be applied.'
complete -c passwd -s l --description 'This option causes the password to be updated in the given location of the ch…'
complete -c passwd -s u --description 'This option specifies the user name to use when authenticating to the directo…'

