# pluginkit
# Autogenerated from man page /usr/share/man/man8/pluginkit.8
complete -c pluginkit -s A --description 'Matches find all versions of a given plug-in known to the system.'
complete -c pluginkit -s a --description 'Explicitly adds plugins at the file location(s) given, even if they are not n…'
complete -c pluginkit -s e --description 'Perform a matching operation (see -m) and apply the given user election setti…'
complete -c pluginkit -s D --description 'Matches find all physical instances of a given plug-in known to the system, e…'
complete -c pluginkit -s i --description 'Specifies a plug-in identifier to match, a short-hand for NSExtensionIdentifi…'
complete -c pluginkit -s m --description 'Requests pluginkit to scan all registered plug-ins for those matching the giv…'
complete -c pluginkit -s p --description 'Specifies a plug-in protocol to  match, a short-hand for NSExtensionPointName…'
complete -c pluginkit -s r --description 'Explicitly removes plugins at the file location(s) given.'
complete -c pluginkit -l raw --description 'Present replies from the management daemon (pkd) in raw XML form.'
complete -c pluginkit -s v --description 'Asks for more verbose operation.'

