# plutil
# Autogenerated from man page /usr/share/man/man1/plutil.1
complete -c plutil -o help --description 'Show the usage information for the command and exit.'
complete -c plutil -s p --description 'Print the property list in a human-readable fashion.'
complete -c plutil -o lint --description 'Check the named property list files for syntax errors.'
complete -c plutil -o convert --description 'Convert the named file to the indicated format and write back to the file sys…'
complete -c plutil -s s --description 'Don\'t print anything on success.'
complete -c plutil -s r --description 'For JSON, add whitespace and indentation to make the output more human-readab…'
complete -c plutil -s o --description 'Specify an alternate path name for the result of the -convert operation; this…'
complete -c plutil -s e --description 'Specify an alternate extension for converted files, and the output file names…'

