# pod2text5
# Autogenerated from man page /usr/share/man/man1/pod2text5.18.1
complete -c pod2text5 -s a -l alt --description 'Use an alternate output format that, among other things, uses a different hea…'
complete -c pod2text5 -l code --description 'Include any non-POD text from the input file in the output as well.'
complete -c pod2text5 -s c -l color --description 'Format the output with \\s-1ANSI\\s0 color escape sequences.'
complete -c pod2text5 -s i -l indent --description 'Set the number of spaces to indent regular text, and the default indentation …'
complete -c pod2text5 -o errors --description 'Set the error handling style.'
complete -c pod2text5 -s h -l help --description 'Print out usage information and exit.'
complete -c pod2text5 -s l -l loose --description 'Print a blank line after a \\f(CW\\*(C`=head1\\*(C\' heading.'
complete -c pod2text5 -s m -l left-margin -l margin --description 'The width of the left margin in spaces.   Defaults to 0.'
complete -c pod2text5 -l nourls --description 'Normally, L<> formatting codes with a \\s-1URL\\s0 but anchor text are formatte…'
complete -c pod2text5 -s o -l overstrike --description 'Format the output with overstrike printing.'
complete -c pod2text5 -s q -l quotes --description 'Sets the quote marks used to surround C<> text to quotes.'
complete -c pod2text5 -s s -l sentence --description 'Assume each sentence ends with two spaces and try to preserve that spacing.'
complete -c pod2text5 -l stderr --description 'By default, pod2text dies if any errors are detected in the \\s-1POD\\s0 input.'
complete -c pod2text5 -s t -l termcap --description 'Try to determine the width of the screen and the bold and underline sequences…'
complete -c pod2text5 -s u -l utf8 --description 'By default, pod2text tries to use the same output encoding as its input encod…'

