# psed
# Autogenerated from man page /usr/share/man/man1/psed.1
complete -c psed -s a --description 'A file specified as argument to the w edit command is by default opened befor…'
complete -c psed -s e --description 'The editing commands defined by script are appended to the script.'
complete -c psed -s f --description 'Editing commands from the specified script-file are read and appended to the …'

