# pstopdf
# Autogenerated from man page /usr/share/man/man1/pstopdf.1
complete -c pstopdf -s o --description 'The name of the output file to create.'
complete -c pstopdf -s i --description 'Reads from stdin rather than a named input file.'
complete -c pstopdf -s l --description 'Specifies that any messages generated during file conversion be written to a …'
complete -c pstopdf -s p --description 'Generates a simple progress message to stdout at the end of each page.'

