# pydoc2
# Autogenerated from man page /usr/share/man/man1/pydoc2.7.1
complete -c pydoc2 -s k --description 'Search for a keyword in the synopsis lines of all available modules.'
complete -c pydoc2 -s p --description 'Start an HTTP server on the given port on the local machine.'
complete -c pydoc2 -s g --description 'Pop up a graphical interface for finding and serving documentation.'
complete -c pydoc2 -s w --description 'Write out the HTML documentation for a module to a file in the current direct…'
complete -c pydoc2 -l help --description 'Prints out a help message.'

