# qtmodernizer
# Autogenerated from man page /usr/share/man/man1/qtmodernizer.1
complete -c qtmodernizer -s h --description '.'
complete -c qtmodernizer -s p --description 'If -p or --useprores is specified, qtmodernizer will use the ProRes video cod…'
complete -c qtmodernizer -o p4 --description 'If -p4 or --useprores4444 is specified, qtmodernizer will use the ProRes4444 …'
complete -c qtmodernizer -s r --description 'Normally qtmodernizer will not replace any existing files.'
complete -c qtmodernizer -s v --description 'Normally qtmodernizer only displays important error or warning messages.'
complete -c qtmodernizer -s i --description 'Causes qtmodernizer to display information about the tracks contained in the …'

