# quotacheck
# Autogenerated from man page /usr/share/man/man8/quotacheck.8
complete -c quotacheck -s a --description 'If the a flag is supplied in place of any filesystem names, quotacheck quotac…'
complete -c quotacheck -s g --description 'Only group quotas are checked.  The mount option file, . quota. ops.'
complete -c quotacheck -s u --description 'Only user quotas are checked.   The mount option file, . quota. ops.'
complete -c quotacheck -s v --description 'quotacheck quotacheck reports discrepancies between the calculated and record…'

