# quotaoff
# Autogenerated from man page /usr/share/man/man8/quotaoff.8
complete -c quotaoff -s a --description 'If the a flag is supplied in place of any filesystem names, quotaoff quotaon …'
complete -c quotaoff -s g --description 'Only group quotas will be enabled/disabled.  The mount option file, . quota.'
complete -c quotaoff -s u --description 'Only user quotas will be enabled/disabled.  The mount option file, . quota.'
complete -c quotaoff -s v --description 'Causes quotaoff quotaon and quotaoff quotaoff to print a message for each fil…'

