# quotaon
# Autogenerated from man page /usr/share/man/man8/quotaon.8
complete -c quotaon -s a --description 'If the a flag is supplied in place of any filesystem names, quotaon quotaon N…'
complete -c quotaon -s g --description 'Only group quotas will be enabled/disabled.  The mount option file, . quota.'
complete -c quotaon -s u --description 'Only user quotas will be enabled/disabled.  The mount option file, . quota.'
complete -c quotaon -s v --description 'Causes quotaon quotaon and quotaon quotaoff to print a message for each files…'

