# raidutil
# Autogenerated from man page /usr/share/man/man8/raidutil.8
complete -c raidutil -s c --description 'This option (controller) allows the user to specify a controller type.'
complete -c raidutil -s h --description 'This option (help) will print the standard "usage" text.'
complete -c raidutil -s t --description 'This option (terse) will minimize superfluous text.'
complete -c raidutil -s v --description 'This option (verbose) will maximize the amount of detailed infomation the pro…'
complete -c raidutil -s V --description 'This option (Version) will print out version information about this program.'

