# rebase
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/rebase.1
complete -c rebase -o low_address --description 'Force the base address for the first image to be addr (specified in hex).'
complete -c rebase -o high_address --description 'Force the base address for the last image to be such that when that image is …'
complete -c rebase -o arch --description 'Only rebase the specified architecture.'
complete -c rebase -s v --description 'Verbose.  Print information about rebasing done.  El SEE ALSO ld 1.'

