# renice
# Autogenerated from man page /usr/share/man/man8/renice.8
complete -c renice -s g --description 'Force who parameters to be interpreted as process group ID\'s.'
complete -c renice -s n --description 'Instead of changing the specified processes to the given priority, interpret …'
complete -c renice -s u --description 'Force the who parameters to be interpreted as user names or user ID\'s.'
complete -c renice -s p --description 'Reset the who interpretation to be (the default) process ID\'s.'

