# repquota
# Autogenerated from man page /usr/share/man/man8/repquota.8
complete -c repquota -s a --description 'Print the quotas of all the filesystems configured with a quota mount option …'
complete -c repquota -s g --description 'Print only group quotas (the default is to print both group and user quotas i…'
complete -c repquota -s u --description 'Print only user quotas (the default is to print both group and user quotas if…'
complete -c repquota -s v --description 'Print a header line before printing each filesystem quotas.'

