# reset
# Autogenerated from man page /usr/share/man/man1/reset.1
complete -c reset -o Ttype --description 'indicates the type of terminal.'
complete -c reset -s S --description 'allows more than one capability per invocation of tput.'
complete -c reset -s V --description 'reports the version of ncurses which was used in this program, and exits.'

