# RezDet
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/RezDet.1
complete -c RezDet -s b --description 'Reads the data for each resource into memory one resource at a time, instead …'
complete -c RezDet -o useDF --description 'Reads and writes resource information from the files\' data forks, instead of …'
complete -c RezDet -o noResolve --description 'Prevents the resolution of leaf aliases in the input resource file path.'
complete -c RezDet -s d --description 'Generates the same information as the -s[how] option as well as detailed info…'
complete -c RezDet -s l --description 'Lists resource types, IDs, names, attributes, and resource sizes.'
complete -c RezDet -s q --description 'Returns a status code instead of generating error messages.'
complete -c RezDet -s r --description 'Generates the same information as the -d[ump] option but also dumps the conte…'
complete -c RezDet -s s --description 'Writes information about individual resource types.'
complete -c RezDet -s 1 --description '.'
complete -c RezDet -s t --description 'Suppresses all messages that do not explicitly describe errors.'

