# rmid
# Autogenerated from man page /usr/share/man/man1/rmid.1
complete -c rmid -s C --description 'Specifies an option that is passed as a command-line argument to each child p…'
complete -c rmid -s J --description 'Specifies an option that is passed to the java interpreter running  rmid .'
complete -c rmid -o 'J-Dsun.rmi.activation.execPolicy' --description 'Specifies the policy that  rmid employs to check commands and command-line op…'
complete -c rmid -o log --description 'Specifies the name of the directory the activation system daemon uses to writ…'
complete -c rmid -o port --description 'Specifies the port  rmid \'s registry uses.'
complete -c rmid -s D --description '.'
complete -c rmid -o stop --description 'Stops the current invocation of rmid ,  for a port specified by the .'

