# route
# Autogenerated from man page /usr/share/man/man8/route.8
complete -c route -s d --description 'Run in debug-only mode, i. e. , do not actually modify the routing table.'
complete -c route -s n --description 'Bypass attempts to print host and network names symbolically when reporting a…'
complete -c route -s t --description 'Run in test-only mode.  /dev/null is used instead of a socket.'
complete -c route -s v --description '(verbose) Print additional details.'
complete -c route -s q --description 'Suppress all output.'

