# rpcsvchost
# Autogenerated from man page /usr/share/man/man8/rpcsvchost.8
complete -c rpcsvchost -o debug --description 'rpcsvchost will log debug information and may perform extra diagnostic checks.'
complete -c rpcsvchost -o endpoints --description 'This argument specifies additional endpoints that rpcsvchost should attempt t…'
complete -c rpcsvchost -o help --description 'Prints a usage message and exits.'
complete -c rpcsvchost -o launchd --description 'Normally, rpcsvchost attempts to bind all the well-known endpoints specified …'
complete -c rpcsvchost -o sandbox --description 'When this option is specified, the modules loaded by rpcsvchost will be run i…'
complete -c rpcsvchost -o register --description 'When this option is specified, rpcsvchost attempts to register the loaded ser…'
complete -c rpcsvchost -o stdout --description 'Causes rpcsvchost to print log messages to standard output instead of the sys…'
complete -c rpcsvchost -o wait-for-debugger --description 'Causes rpcsvchost to wait for a debugger to attach after it has loaded and in…'

