# rtadvd
# Autogenerated from man page /usr/share/man/man8/rtadvd.8
complete -c rtadvd -s c --description 'Specify an alternate location, configfile, for the configuration file.'
complete -c rtadvd -s d --description 'Print debugging information.'
complete -c rtadvd -s D --description 'Even more debugging information is printed.'
complete -c rtadvd -s f --description 'Foreground mode (useful when debugging).'
complete -c rtadvd -s F --description 'Specify an alternative file in which to dump internal states when rtadvd rece…'
complete -c rtadvd -s M --description 'Specify an interface to join the all-routers site-local multicast group.'
complete -c rtadvd -s p --description 'Specify an alternative file in which to store the process ID.'
complete -c rtadvd -s R --description 'Accept router renumbering requests.'
complete -c rtadvd -s s --description 'Do not add or delete prefixes dynamically.'

