# s2p5
# Autogenerated from man page /usr/share/man/man1/s2p5.18.1
complete -c s2p5 -s a --description 'A file specified as argument to the w edit command is by default opened befor…'
complete -c s2p5 -s e --description 'The editing commands defined by script are appended to the script.'
complete -c s2p5 -s f --description 'Editing commands from the specified script-file are read and appended to the …'

