# safaridriver
# Autogenerated from man page /usr/share/man/man1/safaridriver.1
complete -c safaridriver -s p --description 'Specifies the port on which the HTTP server should listen for incoming connec…'
complete -c safaridriver -s h --description 'Prints a usage message and exits.'
complete -c safaridriver -o '\\-enable' --description 'Applies configuration changes so that subsequent WebDriver sessions will run …'

