# sc_usage
# Autogenerated from man page /usr/share/man/man1/sc_usage.1
complete -c sc_usage -s c --description 'When the c option is specified, it expects a path to a codefile that contains…'
complete -c sc_usage -s e --description 'Specifying the e option generates output that is sorted by call count.'
complete -c sc_usage -s l --description 'The l option causes sc_usage sc_usage to turn off its continuous window updat…'
complete -c sc_usage -s s --description 'By default, sc_usage sc_usage updates its output at one second intervals.'

