# scandeps
# Autogenerated from man page /usr/share/man/man1/scandeps.pl.1
complete -c scandeps -s e --description 'Scan \\s-1STRING\\s0 as a string containing perl code.'
complete -c scandeps -s c --description 'Compiles the code and inspects its \\f(CW%INC, in addition to static scanning.'
complete -c scandeps -s x --description 'Executes the code and inspects its \\f(CW%INC, in addition to static scanning.'
complete -c scandeps -s B --description 'Include core modules in the output and the recursive search list.'
complete -c scandeps -s R --description 'Only show dependencies found in the files listed and do not recurse.'
complete -c scandeps -s V --description 'Verbose mode: Output all files found during the process;  show dependencies b…'

