# script
# Autogenerated from man page /usr/share/man/man1/script.1
complete -c script -s a --description 'Append the output to file or typescript, retaining the prior contents.'
complete -c script -s d --description 'When playing back a session with the p flag, do not sleep between records whe…'
complete -c script -s F --description 'Immediately flush output after each write.'
complete -c script -s k --description 'Log keys sent to the program as well as output.'
complete -c script -s p --description 'Play back a session recorded with the r flag in real time.'
complete -c script -s q --description 'Run in quiet mode, omit the start, stop and command status messages.'
complete -c script -s r --description 'Record a session with input, output, and timestamping.'
complete -c script -s t --description 'Specify the interval at which the script output file will be flushed to disk,…'

