# searchstressattr
# Autogenerated from man page /usr/share/man/man1/searchstressattr.1
complete -c searchstressattr -s a --description 'Description of -a flag.'
complete -c searchstressattr -s b --description 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

