# search
# Autogenerated from man page /usr/share/man/man1/search.1
complete -c search -s a --description 'Description of -a flag.'
complete -c search -s b --description 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

