# searchutil
# Autogenerated from man page /usr/share/man/man1/searchutil.1
complete -c searchutil -s a --description 'Description of -a flag.'
complete -c searchutil -s b --description 'Description of -b flag \\" Ends the list Pp FILES                \\" File used …'

