# sed
# Autogenerated from man page /usr/share/man/man1/sed.1
complete -c sed -s E --description 'Interpret regular expressions as extended (modern) regular expressions rather…'
complete -c sed -s a --description 'The files listed as parameters for the w functions are created (or truncated)…'
complete -c sed -s e --description 'Append the editing commands specified by the command argument to the list of …'
complete -c sed -s f --description 'Append the editing commands found in the file command_file to the list of com…'
complete -c sed -s i --description 'Edit files in-place, saving backups with the specified extension.'
complete -c sed -s l --description 'Make output line buffered.'
complete -c sed -s n --description 'By default, each line of input is echoed to the standard output after all of …'

