# segedit
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/segedit.1
complete -c segedit -o extract --description 'Extracts the section specified by the segment name section name pair and plac…'
complete -c segedit -o replace --description 'Will replace the section specified by the segment name section name pair and …'
complete -c segedit -o segcreate --description 'option.'
complete -c segedit -s l --description 'option to  otool (1).'
complete -c segedit -o output --description 'option must also be specified.'

