# serialver
# Autogenerated from man page /usr/share/man/man1/serialver.1
complete -c serialver -o classpath --description 'Set search path for application classes and resources.'
complete -c serialver -o show --description 'Displays a simple user interface.'
complete -c serialver -s J --description 'Pass option to the Java virtual machine, where option is one of the options d…'
complete -c serialver -o J-Xms48m --description 'sets the startup memory to 48 megabytes.  It is a common convention for.'

