# servertool
# Autogenerated from man page /usr/share/man/man1/servertool.1
complete -c servertool -o ORBInitialHost --description 'Specifies the host machine on which the name server  is running and listening…'
complete -c servertool -s J --description 'Pass  option  to the Java virtual machine, where  option is one of the option…'
complete -c servertool -o server --description '.'
complete -c servertool -o classpath --description '[ .'
complete -c servertool -o applicationName --description '.'
complete -c servertool -o args --description '.'
complete -c servertool -o vmargs --description '] Register a new server with the Object Request Broker Daemon (ORBD).'
complete -c servertool -o serverid --description '| .'
complete -c servertool -o endpointType --description '] Locate the endpoints (ports) of a specific type for all ORBs created by a r…'
complete -c servertool -o orbid --description '] Locate all the endpoints (ports) registered by a specific ORB of registered…'

