# SetFile
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/SetFile.1
complete -c SetFile -s P --description 'Acts on a symlink file instead on the file the symlink resolves to.'
complete -c SetFile -s a --description 'Sets the file attributes bits where attributes is a string of case sensitive …'
complete -c SetFile -s c --description 'Specifies the file\'s creator, where creator can be a string of four MacRoman …'
complete -c SetFile -s d --description 'Sets the creation date, where date is a string of the form: "mm/dd/[yy]yy [hh…'
complete -c SetFile -s m --description 'Sets the modification date where date is a string of the form in d above.'
complete -c SetFile -s t --description 'Sets the file type, where type can be a string of four MacRoman characters, a…'

