# setquota
# Autogenerated from man page /usr/share/man/man1/setquota.1
complete -c setquota -s a --description 'sets home directory quota for users defined in all directory domains of the s…'
complete -c setquota -s l --description 'sets home directory quota for users defined in the local directory domain.'
complete -c setquota -s n --description 'sets home directory quota for users defined in a specific directory domain in…'
complete -c setquota -s u --description 'sets home directory quota for a specific user defined in the domain(s) identi…'

