# sharing
# Autogenerated from man page /usr/share/man/man8/sharing.8
complete -c sharing -s a --description 'Add a new share point for the directory specified by <path>.'
complete -c sharing -s e --description 'Edit the share point record specified by <share point name>.'
complete -c sharing -s r --description 'Delete the share point record specified by <share point name>.'
complete -c sharing -s l --description 'List all existing share point records.'
complete -c sharing -s A --description 'Use customized name <afp name> when using share point with afp.'
complete -c sharing -s S --description 'Use customized name <smb name> when using share points with smb.'
complete -c sharing -s s --description 'Use this option to enable and disable sharing via afp and smb.'
complete -c sharing -s g --description 'Use this option to enable and disable guest access for afp and smb.'
complete -c sharing -s i --description 'Use this option to enable and disable the "inherit privileges" attribute for …'
complete -c sharing -s n --description 'Specify a <customized record name> to be used as the share point record name.'

