# shutdown
# Autogenerated from man page /usr/share/man/man8/shutdown.8
complete -c shutdown -s h --description 'The system is halted at the specified time.'
complete -c shutdown -s k --description 'Kick everybody off.'
complete -c shutdown -s n --description 'If the o is specified, prevent the file system cache from being flushed by pa…'
complete -c shutdown -s o --description 'If h or r is specified, shutdown shutdown will execute halt 8 or reboot 8 ins…'
complete -c shutdown -s r --description 'The system is rebooted at the specified time.'
complete -c shutdown -s s --description 'The system is put to sleep at the specified time.'
complete -c shutdown -s u --description 'The system is halted up until the point of removing system power, but waits b…'

