# size
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/size.1
complete -c size -s m --description 'Print the sizes of the Mach-O segments and sections as well as the total size…'
complete -c size -s l --description 'When used with the  -m option, also print the addresses and offsets of the se…'
complete -c size -s x --description 'When used with the  -m option, print the values in hexadecimal (with leading …'
complete -c size -o arch --description 'Specifies the architecture, arch_type, of the file for size (1) to operate on…'

