# skywalkctl
# Autogenerated from man page /usr/share/man/man8/skywalkctl.8
complete -c skywalkctl -s f --description 'Redirect output to the file specified by OUTFILE, instead of stdout.'
complete -c skywalkctl -s I --description 'Re-print channel statistics with a period of interval seconds, until the SIGI…'
complete -c skywalkctl -s D --description 'Provide more details about each provider netns [ -a ] | [ -i, --ip IP -p, --p…'
complete -c skywalkctl -s a --description 'ignore any other specifiers and list the contents of every namespace, one aft…'

