# smbd
# Autogenerated from man page /usr/share/man/man8/smbd.8
complete -c smbd -o debug --description 'The service will log extensive debug information and may perform extra diagno…'
complete -c smbd -o help --description 'Prints a usage message and exits.'
complete -c smbd -o ports --description 'The service will listen on each of the TCP ports specified in the comma-separ…'
complete -c smbd -o stdout --description 'Causes smbd to print log messages to standard output instead of the system lo…'
complete -c smbd -o no-symlinks --description 'In normal operation, smbd will respond to client symlink requests but will ne…'

