# smbdiagnose
# Autogenerated from man page /usr/share/man/man8/smbdiagnose.8
complete -c smbdiagnose -s h --description 'Print full usage.'
complete -c smbdiagnose -s f --description 'Write the diagnostic to the specified path.  The default is ~/Desktop.'
complete -c smbdiagnose -s s --description 'Collect sysdiagnose 1 information.'

