# snmpnetstat
# Autogenerated from man page /usr/share/man/man1/snmpnetstat.1
complete -c snmpnetstat -o Ca --description 'With the default display, show the state of all sockets; normally sockets use…'
complete -c snmpnetstat -o Ci --description 'Show the state of all of the network interfaces.'
complete -c snmpnetstat -o Co --description 'Show an abbreviated interface status, giving octets in place of packets.'
complete -c snmpnetstat -o CI --description 'Show information only about this interface; used with an interval as describe…'
complete -c snmpnetstat -o Cn --description 'Show network addresses as numbers (normally  snmpnetstat interprets addresses…'
complete -c snmpnetstat -o Cp --description 'Show statistics about  protocol, which is either a well-known name for a prot…'
complete -c snmpnetstat -o Cs --description 'Show per-protocol statistics.   When used with the.'
complete -c snmpnetstat -o Cr --description 'option, show routing statistics instead.'
complete -c snmpnetstat -o CR --description 'For GETBULK requests, repeaters specifies the max-repeaters value to use.'

