# sntp
# Autogenerated from man page /usr/share/man/man1/sntp.1
complete -c sntp -o '\\&?' --description 'Display usage information and exit.'
complete -c sntp -o '\\&' --description 'Pass the extended usage information through a pager.'
complete -c sntp -s '>' --description 'Save the option state to \\fIcfgfile\\fP.'
complete -c sntp -s '<' --description 'Load options from \\fIcfgfile\\fP.'
complete -c sntp -o '\\-version' --description 'Output version of program and exit.'

