# spray
# Autogenerated from man page /usr/share/man/man8/spray.8
complete -c spray -s c --description 'Send count packets.'
complete -c spray -s d --description 'Pause delay microseconds between sending each packet.'
complete -c spray -s l --description 'Set the length of the packet that holds the RPC call message to length bytes.'

