# stringdups
# Autogenerated from man page /usr/share/man/man1/stringdups.1
complete -c stringdups -o minimumCount --description 'Only print information for object descriptions which appear at least count ti…'
complete -c stringdups -o stringsOnly --description 'Only print information for objects that have string content such as C or Pasc…'
complete -c stringdups -o nostacks --description 'Do not print stack backtraces or call trees even if the target process has th…'
complete -c stringdups -o callTrees --description 'If stack backtraces are available, then by default all the object description…'
complete -c stringdups -o invertCallTrees --description 'Same as FL callTrees except that the call trees are printed from hottest to c…'

