# strings
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/strings.1
complete -c strings -s a --description 'This option causes  strings to look for strings in all sections of the object…'
complete -c strings -s o --description 'Preceded each string by its offset in the file (in decimal).'
complete -c strings -s t --description 'Write each string preceded by its byte offset from the start of the file.'
complete -c strings -s n --description 'Specify the minimum string length, where the number argument is a positive de…'
complete -c strings -o arch --description 'Specifies the architecture, arch_type, of the file for strings (1) to operate…'

