# stty
# Autogenerated from man page /usr/share/man/man1/stty.1
complete -c stty -s a --description 'Display all the current settings for the terminal to standard output as per -…'
complete -c stty -s e --description 'Display all the current settings for the terminal to standard output in the t…'
complete -c stty -s f --description 'Open and use the terminal named by file rather than using standard input.'
complete -c stty -s g --description 'Display all the current settings for the terminal to standard output in a for…'
complete -c stty -o evenp --description 'Same as oddp and parity.  evenp Enable parenb and cs7 ; disable parodd.'
complete -c stty -o oddp --description 'Same as evenp and parity.  oddp Enable parenb, cs7, and parodd.'
complete -c stty -o parity --description 'Disable parenb ; set cs8.  parity Same as evenp.'

