# su
# Autogenerated from man page /usr/share/man/man1/su.1
complete -c su -s f --description 'If the invoked shell is csh 1, this option prevents it from reading the .'
complete -c su -s l --description 'Simulate a full login.'
complete -c su -s m --description 'Leave the environment unmodified.'

