# syslogd
# Autogenerated from man page /usr/share/man/man8/syslogd.8
complete -c syslogd -s d --description 'Run syslogd in debugging mode.'
complete -c syslogd -s D --description 'Start as a daemon.'
complete -c syslogd -s m --description 'Set the number of minutes between mark messages.'
complete -c syslogd -o db_max --description 'Sets the size limit in bytes for individual files in the data store.'
complete -c syslogd -o utmp_ttl --description 'Sets the time-to-live in seconds for messages used by the utmp, wtmp, and las…'
complete -c syslogd -o mps_limit --description 'Sets the kernel quota for messages per second allowed by syslogd.'
complete -c syslogd -o dup_delay --description 'Sets the time to delay for coalescing duplicate message in log files.'
complete -c syslogd -o asl_in --description 'The asl_in module receives log messages on the UNIX domain socket associated …'
complete -c syslogd -o asl_action --description 'The asl_action module examines the stream of received log messages and acts u…'
complete -c syslogd -o klog_in --description 'The klog_in module receives log messages on the UNIX domain socket associated…'
complete -c syslogd -o bsd_in --description 'The bsd_in module receives log messages on the UNIX domain socket associated …'
complete -c syslogd -o bsd_out --description 'The bsd_out module examines the stream of received log messages and acts upon…'
complete -c syslogd -o udp_in --description 'The udp_in module receives log messages on the UDP socket associated with the…'

