# systemkeychain
# Autogenerated from man page /usr/share/man/man8/systemkeychain.8
complete -c systemkeychain -s C --description 'Create a keychain and establish it in the system as the primary system keycha…'
complete -c systemkeychain -s s --description 'Extract the master secret from source keychain(s) and install them in a desti…'
complete -c systemkeychain -s t --description 'Test unlocking the system keychain.'
complete -c systemkeychain -s k --description 'Use a keychain other than the default as the destination system keychain.'
complete -c systemkeychain -s c --description 'Create the target keychain if necessary.'
complete -c systemkeychain -s f --description 'Force creation of a system keychain or overwriting of an existing key for key…'
complete -c systemkeychain -s v --description 'Turn on verbose mode.'

