# tailspin
# Autogenerated from man page /usr/share/man/man1/tailspin.1
complete -c tailspin -s r --description 'Include a key in the tailspin file indicating why it was saved.'
complete -c tailspin -s l --description 'Limit the data in tailspin file to that of the last num-seconds.'
complete -c tailspin -s n --description 'Save tailspin file without symbolicating.'
complete -c tailspin -s v --description 'Print layout information of tailspin file.'
complete -c tailspin -s s --description 'Sort ktrace statistics by frequency of trace class/subclass.'

