# talagent
# Autogenerated from man page /usr/share/man/man8/talagent.8
complete -c talagent -o help --description 'Outputs usage information.'
complete -c talagent -o dump --description 'Outputs the persistent state of an application whose bundle ID contains the g…'
complete -c talagent -o launch --description 'This launches an app (in this case, TextEdit) in a manner approximating how a…'
complete -c talagent -o memory_pressure --description 'Simulates memory pressure, which may cause apps that support automatic termin…'
complete -c talagent -o refresh_encryption --description 'Rotates the bitmap encryption key, and attempts to cross-encrypt all existing…'

