# tapi-stubify
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/tapi-stubify.1
complete -c tapi-stubify -l no-uuids --description '.'
complete -c tapi-stubify -l set-installapi-flag --description '.'
complete -c tapi-stubify -l inline-private-frameworks --description '.'
complete -c tapi-stubify -s o --description '.'
complete -c tapi-stubify -o isysroot --description '.'
complete -c tapi-stubify -l help --description '.'

