# tapi-archive
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/tapi-archive.1
complete -c tapi-archive -l info --description '.'
complete -c tapi-archive -l verify-arch --description '.'
complete -c tapi-archive -l extract --description '.'
complete -c tapi-archive -l merge --description '.'
complete -c tapi-archive -s o --description '.'
complete -c tapi-archive -l help --description '.'
complete -c tapi-archive -l version --description '.'

