# taskpolicy
# Autogenerated from man page /usr/share/man/man8/taskpolicy.8
complete -c taskpolicy -s d --description 'Run the program after calling setiopolicy_np 3 with an iotype of IOPOL_TYPE_D…'
complete -c taskpolicy -s g --description 'Run the program after calling setiopolicy_np 3 with an iotype of IOPOL_TYPE_D…'
complete -c taskpolicy -s c --description 'Run the program using the specified QoS clamp.'
complete -c taskpolicy -s p --description 'Change settings for the process specified by pid.'
complete -c taskpolicy -s b --description 'Run the program after calling setpriority 2 with a priority of PRIO_DARWIN_BG.'
complete -c taskpolicy -s B --description 'Move target process out of PRIO_DARWIN_BG.'
complete -c taskpolicy -s t --description 'Set throughput tier of the process to thruput_tier.'
complete -c taskpolicy -s l --description 'Set latency tier of the process to latency_tier.'
complete -c taskpolicy -s a --description 'Run the program with the resource management policies given to applications.'

