# tiff2icns
# Autogenerated from man page /usr/share/man/man1/tiff2icns.1
complete -c tiff2icns -o noLarge --description 'tiff2icns always creates a large 32x32 icon unless the \\fB-noLarge\\fR flag is…'

