# tops
# Autogenerated from man page /usr/share/man/man1/tops.1
complete -c tops -o help --description 'Displays the tops syntax line.'
complete -c tops -o verbose --description 'Prints out the source code lines that are being changed by the command.'
complete -c tops -o nocontext --description 'Instead of printing the whole source code line that is being changed or searc…'
complete -c tops -o nofileinfo --description 'Does not print the file name and line number information in verbose messages.'
complete -c tops -o semiverbose --description 'Shows how much of the file has been processed.'
complete -c tops -o dont --description 'Shows what changes would be made to the source code without actually performi…'
complete -c tops -o scriptfile --description 'Specifies the script file containing the rules that tops will apply to your c…'
complete -c tops -o classfile --description 'Specifies a file that describes the class hierarchy used by the files being p…'

