# touch
# Autogenerated from man page /usr/share/man/man1/touch.1
complete -c touch -s A --description 'Adjust the access and modification time stamps for the file by the specified …'
complete -c touch -s a --description 'Change the access time of the file.'
complete -c touch -s c --description 'Do not create the file if it does not exist.'
complete -c touch -s f --description 'Attempt to force the update, even if the file permissions do not currently pe…'
complete -c touch -s h --description 'If the file is a symbolic link, change the times of the link itself rather th…'
complete -c touch -s m --description 'Change the modification time of the file.'
complete -c touch -s r --description 'Use the access and modifications times from the specified file instead of the…'
complete -c touch -s t --description 'Change the access and modification times to the specified time instead of the…'

