# tr
# Autogenerated from man page /usr/share/man/man1/tr.1
complete -c tr -s C --description 'Complement the set of characters in string1, that is C Li ab includes every c…'
complete -c tr -s c --description 'Same as C but complement the set of values in string1.'
complete -c tr -s d --description 'Delete characters in string1 from the input.'
complete -c tr -s s --description 'Squeeze multiple occurrences of the characters listed in the last operand (ei…'
complete -c tr -s u --description 'Guarantee that any output is unbuffered.'

