# tsort
# Autogenerated from man page /usr/share/man/man1/tsort.1
complete -c tsort -s l --description 'Search for and display the longest cycle.  Can take a very long time.'
complete -c tsort -s q --description 'Do not display informational messages about cycles.'

