# umount
# Autogenerated from man page /usr/share/man/man8/umount.8
complete -c umount -s a --description 'All the filesystems described via getfsent 3 are unmounted.'
complete -c umount -s A --description 'All the currently mounted filesystems except the root are unmounted.'
complete -c umount -s f --description 'The filesystem is forcibly unmounted.'
complete -c umount -s h --description 'Only filesystems mounted from the specified host will be unmounted.'
complete -c umount -s t --description 'Is used to indicate the actions should only be taken on filesystems of the sp…'
complete -c umount -s v --description 'Verbose, additional information is printed out as each filesystem is unmounte…'

