# unbound
# Autogenerated from man page /usr/share/man/man8/unbound.8
complete -c unbound -s h --description 'Show the version and commandline option help.'
complete -c unbound -s c --description 'Set the config file with settings for unbound to read instead of reading the …'
complete -c unbound -s d --description 'Debug flag: do not fork into the background, but stay attached to the console.'
complete -c unbound -s v --description 'Increase verbosity.  If given multiple times, more information is logged.'

