# uniq
# Autogenerated from man page /usr/share/man/man1/uniq.1
complete -c uniq -s c --description 'Precede each output line with the count of the number of times the line occur…'
complete -c uniq -s d --description 'Only output lines that are repeated in the input.'
complete -c uniq -s f --description 'Ignore the first num fields in each input line when doing comparisons.'
complete -c uniq -s s --description 'Ignore the first chars characters in each input line when doing comparisons.'
complete -c uniq -s u --description 'Only output lines that are not repeated in the input.'
complete -c uniq -s i --description 'Case insensitive comparison of lines.'

