# update_dyld_shared_cache
# Autogenerated from man page /usr/share/man/man1/update_dyld_shared_cache.1
complete -c update_dyld_shared_cache -o root --description 'This option specifies the root of an OS installation for which dyld\'s shared …'
complete -c update_dyld_shared_cache -o overlay --description 'This option specifies the root of a sparse directory tree.'
complete -c update_dyld_shared_cache -o arch --description 'By default update_dyld_shared_cache update_dyld_shared_cache generates cache …'
complete -c update_dyld_shared_cache -o force --description 'This option will cause update_dyld_shared_cache update_dyld_shared_cache to r…'
complete -c update_dyld_shared_cache -o debug --description 'This option prints out additional information about the work being done.'
complete -c update_dyld_shared_cache -o universal_boot --description 'This option builds caches for all machines.  El SEE ALSO dyld 1.'

