# usbdump
# Autogenerated from man page /usr/share/man/man1/usbdump.1
complete -c usbdump -s b --description 'Store data part of the USB trace in binary format to the given file.'
complete -c usbdump -s i --description 'Listen on USB bus interface ifname.'
complete -c usbdump -s r --description 'Read the raw packets from file.  This option also works with the -f option.'
complete -c usbdump -s s --description 'Snapshot snaplen bytes from each packet.'
complete -c usbdump -s v --description 'Enable debugging messages.'
complete -c usbdump -s w --description 'Write the raw packets to file.'
complete -c usbdump -s f --description 'The filter argument consists of either one or two numbers separated by a dot.'
complete -c usbdump -s l --description 'The filter argument consists of either one or two numbers separated by a dot.'
complete -c usbdump -s h --description 'This option displays a summary of the command line options.'

