# uuchk
# Autogenerated from man page /usr/share/man/man8/uuchk.8
complete -c uuchk -s s -l system --description 'Display the configuration for just the specified system, rather than for all …'
complete -c uuchk -s I -l config --description 'Set configuration file to use.'
complete -c uuchk -s v -l version --description 'Report version information and exit.'
complete -c uuchk -l help --description 'Print a help message and exit.'

