# vis
# Autogenerated from man page /usr/share/man/man1/vis.1
complete -c vis -s b --description 'Turns off prepending of backslash before up-arrow control sequences and meta …'
complete -c vis -s c --description 'Request a format which displays a small subset of the non-printable character…'
complete -c vis -s F --description 'Causes vis to fold output lines to foldwidth columns (default 80), like fold …'
complete -c vis -s f --description 'Same as F.'
complete -c vis -s l --description 'Mark newlines with the visible sequence \\e$, followed by the newline.'
complete -c vis -s n --description 'Turns off any encoding, except for the fact that backslashes are still double…'
complete -c vis -s o --description 'Request a format which displays non-printable characters as an octal number, …'
complete -c vis -s s --description 'Only characters considered unsafe to send to a terminal are encoded.'
complete -c vis -s t --description 'Tabs are also encoded.'
complete -c vis -s w --description 'White space (space-tab-newline) is also encoded.'

