# visudo
# Autogenerated from man page /usr/share/man/man8/visudo.8
complete -c visudo -l with-env-editor --description 'option or the env_editor Default variable is set in sudoers, visudo will use …'
complete -c visudo -s c -l check --description 'Enable check-only mode.'
complete -c visudo -s q --description 'option was specified.'
complete -c visudo -s f -l file --description 'Specify an alternate sudoers file location.'
complete -c visudo -s h -l help --description 'Display a short help message to the standard output and exit.'
complete -c visudo -l quiet --description 'Enable quiet mode.  In this mode details about syntax errors are not printed.'
complete -c visudo -s s -l strict --description 'Enable strict checking of the sudoers file.'
complete -c visudo -s V -l version --description 'Print the visudo and sudoers grammar versions and exit.'
complete -c visudo -s x -l export --description 'Export a sudoers in JSON format and write it to output_file.'

