# vmmap
# Autogenerated from man page /usr/share/man/man1/vmmap.1
complete -c vmmap -s w --description 'Print wide output, to show full paths of mapped files.'
complete -c vmmap -s v --description 'Equivalent to w submap allSplitLibs noCoalesce.'
complete -c vmmap -o pages --description 'Print region sizes in page counts rather than kilobytes.'
complete -c vmmap -o interleaved --description 'Print all regions in ascending order of starting address, rather than printin…'
complete -c vmmap -o submap --description 'Print information about VM submaps.'
complete -c vmmap -o allSplitLibs --description 'Print information about all shared system split libraries, even those not loa…'
complete -c vmmap -o noCoalesce --description 'Do not coalesce adjacent identical regions.'
complete -c vmmap -o summary --description 'Print only the summary of VM usage, not the individual region detail.'

