# vpnd
# Autogenerated from man page /usr/share/man/man8/vpnd.8
complete -c vpnd -s d --description 'Do not move to background and print log strings to the terminal.'
complete -c vpnd -s h --description 'Print usage summary and exit.'
complete -c vpnd -s i --description 'Server_id in the plist file that defines the configuration to be run.'
complete -c vpnd -s n --description 'Do not move to background, print log information to the terminal, and quit af…'
complete -c vpnd -s x --description 'Do not move to background.'

