# which
# Autogenerated from man page /usr/share/man/man1/which.1
complete -c which -s a --description 'List all instances of executables found (instead of just the first one of eac…'
complete -c which -s s --description 'No output, just return 0 if all of the executables are found, or 1 if some we…'

