# wsimport
# Autogenerated from man page /usr/share/man/man1/wsimport.1
complete -c wsimport -s d --description 'Specify where to place generated output files.'
complete -c wsimport -s b --description 'Specify external JAX-WS or JAXB binding files (Each file must have its own \\f…'
complete -c wsimport -o catalog --description 'Specify catalog file to resolve external entity references, it supports TR940…'
complete -c wsimport -o extension --description 'Allow vendor extensions (functionality not specified by the specification).'
complete -c wsimport -o help --description 'Display help.'
complete -c wsimport -o httpproxy --description 'Specify an HTTP proxy server (port defaults to 8080).'
complete -c wsimport -o keep --description 'Keep generated files.'
complete -c wsimport -s p --description 'Specifying a target package via this command-line option, overrides any wsdl …'
complete -c wsimport -s s --description 'Specify where to place generated source files.'
complete -c wsimport -o verbose --description 'Output messages about what the compiler is doing.'
complete -c wsimport -o version --description 'Print version information.'
complete -c wsimport -o wsdllocation --description '@WebService. wsdlLocation and @WebServiceClient. wsdlLocation value .'

