# xargs
# Autogenerated from man page /usr/share/man/man1/xargs.1
complete -c xargs -s 0 --description 'Change xargs to expect NUL (``\\\\0\'\') characters as separators, instead of spa…'
complete -c xargs -s E --description 'Use eofstr as a logical EOF marker.'
complete -c xargs -s I --description 'Execute utility for each input line, replacing one or more occurrences of rep…'
complete -c xargs -s J --description 'If this option is specified, xargs will use the data read from standard input…'
complete -c xargs -s L --description 'Call utility for every number non-empty lines read.'
complete -c xargs -s n --description 'Set the maximum number of arguments taken from standard input for each invoca…'
complete -c xargs -s o --description 'Reopen stdin as /dev/tty in the child process before executing the command.'
complete -c xargs -s P --description 'Parallel mode: run at most maxprocs invocations of utility at once.'
complete -c xargs -s p --description 'Echo each command to be executed and ask the user whether it should be execut…'
complete -c xargs -s R --description 'Specify the maximum number of arguments that I will do replacement in.'
complete -c xargs -s s --description 'Set the maximum number of bytes for the command line length provided to utili…'
complete -c xargs -s t --description 'Echo the command to be executed to standard error immediately before it is ex…'
complete -c xargs -s x --description 'Force xargs to terminate immediately if a command line containing number argu…'

