# xattr
# Autogenerated from man page /usr/share/man/man1/xattr.1
complete -c xattr -s l --description 'By default, the first two command forms either displays just the attribute na…'
complete -c xattr -s r --description 'If a file argument is a directory, act as if the entire contents of the direc…'
complete -c xattr -s s --description 'If a file argument is a symbolic link, act on the symbolic link itself, rathe…'
complete -c xattr -s v --description 'Force the the file name to be displayed, even for a single file.'
complete -c xattr -s x --description 'Force the attribute value to be displayed in the hexadecimal representation.'

