# xcode-select
# Autogenerated from man page /usr/share/man/man1/xcode-select.1
complete -c xcode-select -s h -l help --description 'Prints the usage message.'
complete -c xcode-select -s s -l switch --description 'Sets the active developer directory to the given path, for example /Applicati…'
complete -c xcode-select -s p -l print-path --description 'Prints the path to the currently selected developer directory.'
complete -c xcode-select -s r -l reset --description 'Unsets any user-specified developer directory, so that the developer director…'
complete -c xcode-select -s v -l version --description 'Prints xcode-select version information.'
complete -c xcode-select -l install --description 'Opens a user interface dialog to request automatic installation of the comman…'

