# xssendevent
# Autogenerated from man page /usr/share/man/man8/xssendevent.8
complete -c xssendevent -s e --description 'Tells xssendevent to load a file of events in text plist format, one "event" …'

