# ypbind
# Autogenerated from man page /usr/share/man/man8/ypbind.8
complete -c ypbind -o ypset --description 'ypset 8 may be used to change the server to which a domain is bound.'
complete -c ypbind -o ypsetme --description 'ypset 8 may be used only from this machine to change the server to which a do…'
complete -c ypbind -o insecure --description 'permit binding to a ypserv 8 on a non-reserved port.'
complete -c ypbind -s d --description 'enable debugging output.'

