# zic
# Autogenerated from man page /usr/share/man/man8/zic.8
complete -c zic -l version --description 'Output version information and exit.'
complete -c zic -s D --description 'Do not automatically create directories.'
complete -c zic -s d --description 'Create time conversion information files in the named directory rather than i…'
complete -c zic -s g --description 'After creating each output file, change its group ownership to the specified …'
complete -c zic -s L --description 'Read leap second information from the file with the given name.'
complete -c zic -s l --description 'Use the given time zone as local time.'
complete -c zic -s m --description 'After creating each output file, change its access mode to mode.'
complete -c zic -s p --description 'Use the given "time zone" Ns \'s rules when handling POSIX-format time zone en…'
complete -c zic -s u --description 'After creating each output file, change its owner to user (which can be eithe…'
complete -c zic -s v --description 'Complain if a year that appears in a data file is outside the range of years …'
complete -c zic -s s --description 'Limit time values stored in output files to values that are the same whether …'
complete -c zic -s y --description 'Use the given command rather than yearistype when checking year types (see be…'

