# znew
# Autogenerated from man page /usr/share/man/man1/znew.1
complete -c znew -s f --description 'Overwrite existing . gz files.'
complete -c znew -s t --description 'Test integrity of the gzipped file before deleting the original file.'
complete -c znew -s v --description 'Print a report specifying the achieved compression ratios.'
complete -c znew -s 9 --description 'Use the -9 mode of gzip 1, achieving better compression at the cost of slower…'
complete -c znew -s K --description 'Keep the original . Z file if it uses less disk blocks than the gzipped one.'

