# zprint
# Autogenerated from man page /usr/share/man/man1/zprint.1
complete -c zprint -s c --description '(Default) zprint prints zone info in columns.'
complete -c zprint -s d --description 'Display deltas over time, showing any zones that have achieved a new maximum …'
complete -c zprint -s h --description '(Default) Shows headings for the columns printed with the c option.'
complete -c zprint -s l --description '(Default) Show all wired memory information after the zone information.'
complete -c zprint -s L --description 'Do not show all wired memory information after the zone information.'
complete -c zprint -s s --description 'zprint sorts the zones, showing the zone wasting the most memory first.'
complete -c zprint -s t --description 'For each zone, zprint calculates the total size of allocations from the zone …'
complete -c zprint -s w --description 'For each zone, zprint calculates how much space is allocated but not currentl…'

